// The original 8 hardcoded gallery items, reshaped for congoGalleryItems.
// Used only by the one-time admin "seed" action in CongoGallery.jsx —
// not read anywhere else at runtime. Nothing here is deleted or replaced
// by later phases; new items get their own seed/entry, these stay put.
const SEED_ITEMS = [
  {
    slug: "fally-ipupa",
    name: "Fally Ipupa",
    category: "Music",
    shortDescription:
      "A modern Congolese music icon who brought Congolese sound to the world.",
    localImageKey: "fally-ipupa",
    keywords: ["musician", "singer", "rumba"],
    aliases: ["Fally"],
    active: true,
    featured: true,
    verified: true,
  },
  {
    slug: "koffi-olomide",
    name: "Koffi Olomidé",
    category: "Music",
    shortDescription:
      "One of the major voices of Congolese rumba and African music.",
    localImageKey: "koffi-olomide",
    keywords: ["musician", "rumba"],
    aliases: ["Koffi"],
    active: true,
    featured: false,
    verified: true,
  },
  {
    slug: "franco-luambo",
    name: "Franco Luambo",
    category: "Music",
    shortDescription:
      "A legendary figure whose music helped shape Congolese identity.",
    localImageKey: "franco-luambo",
    keywords: ["musician", "rumba", "tpok jazz"],
    aliases: ["Franco"],
    active: true,
    featured: false,
    verified: true,
  },
  {
    slug: "joseph-kabila",
    name: "Joseph Kabila",
    category: "Politics",
    subcategory: "Head of State",
    shortDescription:
      "President of the DRC from 2001 to 2019, succeeding his father Laurent-Désiré Kabila after his assassination.",
    fullBiography:
      "Joseph Kabila became president in January 2001 following the assassination of his father, Laurent-Désiré Kabila, initially as the country's youngest head of state. His presidency spanned the end of the Second Congo War, the 2006 and 2011 elections, and a prolonged period (2016–2019) in which he remained in office past the end of his constitutional mandate before the 2018 election. He was succeeded by Félix Tshisekedi in January 2019.",
    birthDate: "1971-06-04",
    birthplace: "Fizi, South Kivu",
    province: "South Kivu",
    localImageKey: "joseph-kabila",
    keywords: ["president", "politics", "head of state", "kabila"],
    aliases: [],
    active: true,
    featured: true,
    verified: true,
  },
  {
    slug: "kinshasa",
    name: "Kinshasa",
    category: "Cities",
    province: "Kinshasa",
    country: "DR Congo",
    shortDescription:
      "The capital city, full of energy, music, politics, creativity, and movement.",
    localImageKey: "kinshasa",
    keywords: ["capital", "city"],
    active: true,
    featured: true,
    verified: true,
  },
  {
    slug: "boulevard-du-30-juin",
    name: "Boulevard du 30 Juin",
    category: "Cities",
    city: "Kinshasa",
    country: "DR Congo",
    shortDescription:
      "One of Kinshasa’s most symbolic roads, representing movement and national life.",
    localImageKey: "boulevard-du-30-juin",
    keywords: ["boulevard", "30 juin", "kinshasa"],
    active: true,
    featured: false,
    verified: true,
  },
  {
    slug: "eastern-congo",
    name: "Eastern Congo",
    category: "History",
    subcategory: "Memory & Crisis",
    shortDescription:
      "A place of pain, resilience, and courage. Congo Unity remembers the East.",
    localImageKey: "eastern-congo",
    keywords: ["crisis", "kivu", "memory"],
    active: true,
    featured: false,
    verified: true,
  },
  {
    slug: "flag-of-the-drc",
    name: "Flag of the DRC",
    category: "Culture",
    subcategory: "National Symbol",
    shortDescription:
      "The flag reminds us that we are one people, even when everything tries to divide us.",
    localImageKey: "flag-of-the-drc",
    keywords: ["flag", "symbol", "national"],
    active: true,
    featured: true,
    verified: true,
  },

  // ---- Phase 2 additions below: no local photo exists for these 7, so
  // each uses a verified, freely-licensed image from Wikimedia Commons
  // instead (license + photographer checked individually, not assumed —
  // see sourceUrl/sourceName for attribution). Dates are only included
  // where a specific source confirmed them; left blank otherwise rather
  // than guessed.
  {
    slug: "werrason",
    name: "Werrason",
    category: "Music",
    subcategory: "Soukous / Ndombolo",
    shortDescription:
      "Congolese musician and bandleader of Wenge Musica Maison Mère, originally part of Wenge Musica; one of the leading soukous/ndombolo artists of the 1990s–2000s.",
    birthDate: "1965",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/8/8e/Werrason.jpg",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Werrason.jpg",
    sourceName: "Photo via Wikimedia Commons (CC BY-SA)",
    keywords: ["musician", "wenge musica", "soukous", "ndombolo"],
    aliases: [],
    active: true,
    featured: false,
    verified: true,
  },
  {
    slug: "papa-wemba",
    name: "Papa Wemba",
    category: "Music",
    subcategory: "Rumba Rock",
    shortDescription:
      "Congolese singer and a founding figure of \"Congolese rumba rock,\" closely associated with the Sape fashion movement; co-founded Zaiko Langa Langa before leading his own groups.",
    birthDate: "1949-06-14",
    deathDate: "2016-04-24",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/6/63/Papa_Wemba.jpg",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Papa_Wemba.jpg",
    sourceName: "Photo: Radio Okapi via Wikimedia Commons (CC BY 2.0)",
    keywords: ["musician", "zaiko langa langa", "sape", "rumba rock"],
    aliases: [],
    active: true,
    featured: false,
    verified: true,
  },
  {
    slug: "tabu-ley-rochereau",
    name: "Tabu Ley Rochereau",
    category: "Music",
    subcategory: "Rumba",
    shortDescription:
      "Legendary singer and bandleader (African Fiesta, later Afrisa International); one of the most important figures of Congolese rumba's golden era from the 1960s onward.",
    birthDate: "1940-11-13",
    deathDate: "2013-11-30",
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/6/66/Press_photo_of_Tabu_Ley_Rochereau_in_San_Francisco_%281980%29.jpg",
    sourceUrl:
      "https://commons.wikimedia.org/wiki/File:Press_photo_of_Tabu_Ley_Rochereau_in_San_Francisco_(1980).jpg",
    sourceName: "Photo: Philip Gould / The Rosebud Agency, via Wikimedia Commons (public domain)",
    keywords: ["musician", "african fiesta", "afrisa international", "rumba"],
    aliases: ["Rochereau"],
    active: true,
    featured: false,
    verified: true,
  },
  {
    slug: "tshala-muana",
    name: "Tshala Muana",
    category: "Music",
    subcategory: "Mutuashi",
    shortDescription:
      "Celebrated singer and dancer known as the \"Queen of Mutuashi,\" a traditional Congolese dance she helped popularize internationally; prominent from the 1980s.",
    birthDate: "1958-03-13",
    deathDate: "2022-12-10",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/8/8c/Tshala_muana_2015.jpg",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Tshala_muana_2015.jpg",
    sourceName: "Photo via Wikimedia Commons (CC BY-SA 4.0)",
    keywords: ["musician", "dancer", "mutuashi"],
    aliases: [],
    active: true,
    featured: false,
    verified: true,
  },
  {
    slug: "mbilia-bel",
    name: "Mbilia Bel",
    category: "Music",
    subcategory: "Rumba",
    shortDescription:
      "Congolese singer, one of the most prominent female voices in Congolese rumba; rose to fame performing with Tabu Ley Rochereau's Afrisa International in the 1980s before a solo career.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/a/ae/Mbilia_Bel%2C_Zaire.jpg",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Mbilia_Bel,_Zaire.jpg",
    sourceName: "Photo via Wikimedia Commons (public domain, CC0)",
    keywords: ["musician", "afrisa international", "rumba"],
    aliases: ["M'bilia Bel"],
    active: true,
    featured: false,
    verified: true,
  },
  {
    slug: "ferre-gola",
    name: "Ferre Gola",
    category: "Music",
    subcategory: "Rumba / Ndombolo",
    shortDescription:
      "Congolese singer and former member of Wenge Musica BCBG, known for his vocal range; a prominent rumba/ndombolo artist since the 2000s.",
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/f/f1/Ferr%C3%A9_Gola_2024_performance.jpg",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Ferr%C3%A9_Gola_2024_performance.jpg",
    sourceName: "Photo via Wikimedia Commons (CC BY 4.0)",
    keywords: ["musician", "wenge musica bcbg", "ndombolo"],
    aliases: ["Ferré Gola"],
    active: true,
    featured: false,
    verified: true,
  },
  {
    slug: "innossb",
    name: "Innoss'B",
    category: "Music",
    subcategory: "Afrobeat / Hip-Hop",
    shortDescription:
      "Contemporary Congolese singer, part of a newer generation blending Congolese rumba with Afrobeat and hip-hop influences.",
    birthDate: "1997-05-05",
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/6/67/Innoss%27B_%2821600557166%29.jpg",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Innoss'B_(21600557166).jpg",
    sourceName: "Photo: Abel Kavanagh / MONUSCO, via Wikimedia Commons (CC BY-SA 2.0)",
    keywords: ["musician", "rapper", "afrobeat"],
    aliases: ["Innoss B", "Innocent Balume"],
    active: true,
    featured: false,
    verified: true,
  },

  // ---- Politics: figures. Images verified individually on Wikimedia
  // Commons the same way as the Music section (license + author checked
  // per file, not assumed). Dates left blank where genuinely uncertain
  // in the historical record (e.g. Kasa-Vubu's exact birth date) rather
  // than guessed.
  {
    slug: "patrice-lumumba",
    name: "Patrice Lumumba",
    category: "Politics",
    subcategory: "Head of Government",
    shortDescription:
      "First Prime Minister of the independent Republic of the Congo in 1960; assassinated in 1961.",
    fullBiography:
      "Patrice Émery Lumumba led the independence movement that ended Belgian colonial rule and became the country's first Prime Minister when independence was declared on June 30, 1960. His government fell within months amid the Congo Crisis, and he was arrested, then killed in January 1961 in circumstances involving Congolese and Belgian actors that have been the subject of extensive historical investigation. He remains one of the most significant symbols of African independence.",
    birthDate: "1925-07-02",
    deathDate: "1961-01-17",
    birthplace: "Onalua, Kasai",
    province: "Kasai",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/d/d5/Patrice_Lumumba_official_portrait.jpg",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Patrice_Lumumba_official_portrait.jpg",
    sourceName: "Official 1960 government portrait, via Wikimedia Commons (public domain)",
    keywords: ["prime minister", "independence", "politics", "congo crisis"],
    aliases: ["Patrice Émery Lumumba"],
    active: true,
    featured: true,
    verified: true,
  },
  {
    slug: "joseph-kasa-vubu",
    name: "Joseph Kasa-Vubu",
    category: "Politics",
    subcategory: "Head of State",
    shortDescription:
      "First President of the independent Republic of the Congo, serving from 1960 to 1965.",
    fullBiography:
      "Joseph Kasa-Vubu was a founding leader of the ABAKO political party and became the country's first President at independence in June 1960. He remained in office through the turbulent Congo Crisis years until he was deposed in a 1965 coup led by Joseph-Désiré Mobutu.",
    deathDate: "1969-03-24",
    province: "Kongo Central",
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/f/ff/Joseph_Kasa-Vubu_in_1960_%28cropped%29.jpg",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Joseph_Kasa-Vubu_in_1960_(cropped).jpg",
    sourceName: "Photo: Anefo / Dutch National Archives, via Wikimedia Commons (CC0)",
    keywords: ["president", "independence", "abako", "politics"],
    aliases: [],
    active: true,
    featured: false,
    verified: true,
  },
  {
    slug: "mobutu-sese-seko",
    name: "Mobutu Sese Seko",
    category: "Politics",
    subcategory: "Head of State",
    shortDescription:
      "President from 1965 to 1997, ruling for over three decades after taking power in a coup and renaming the country Zaire.",
    fullBiography:
      "Joseph-Désiré Mobutu seized power in a 1965 coup and ruled for 32 years, renaming the country Zaire in 1971 and himself Mobutu Sese Seko. His long rule was marked by centralized one-party control and a personality cult, alongside widely documented corruption and human rights abuses. He was overthrown in 1997 during the First Congo War by forces led by Laurent-Désiré Kabila, and died in exile later that year.",
    birthDate: "1930-10-14",
    deathDate: "1997-09-07",
    birthplace: "Lisala, Équateur",
    province: "Équateur",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/7/7e/Mobutu_Sese_Seko%2C_1969.jpg",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Mobutu_Sese_Seko,_1969.jpg",
    sourceName: "Photo: © European Union, via Wikimedia Commons (attribution required)",
    keywords: ["president", "zaire", "coup", "politics", "dictator"],
    aliases: ["Joseph-Désiré Mobutu"],
    active: true,
    featured: true,
    verified: true,
  },
  {
    slug: "laurent-desire-kabila",
    name: "Laurent-Désiré Kabila",
    category: "Politics",
    subcategory: "Head of State",
    shortDescription:
      "President from 1997 to 2001, having led the rebellion that overthrew Mobutu in the First Congo War.",
    fullBiography:
      "Laurent-Désiré Kabila led the AFDL rebel coalition that overthrew Mobutu Sese Seko in 1997, becoming president and renaming Zaire back to the Democratic Republic of the Congo. His presidency was soon consumed by the outbreak of the Second Congo War in 1998. He was assassinated by a bodyguard in January 2001 and was succeeded by his son, Joseph Kabila.",
    birthDate: "1939-11-27",
    deathDate: "2001-01-16",
    birthplace: "Baudouinville (Moba), Tanganyika",
    province: "Tanganyika",
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/6/6d/Laurent_D%C3%A9sir%C3%A9_Kabila_portrait_3x4.jpg",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Laurent_D%C3%A9sir%C3%A9_Kabila_portrait_3x4.jpg",
    sourceName: "Photo: Etienne Scholasse / European Communities, via Wikimedia Commons (CC BY 4.0)",
    keywords: ["president", "afdl", "first congo war", "politics"],
    aliases: [],
    active: true,
    featured: false,
    verified: true,
  },
  {
    slug: "felix-tshisekedi",
    name: "Félix Tshisekedi",
    category: "Politics",
    subcategory: "Head of State",
    shortDescription:
      "President of the DRC since January 2019, re-elected in 2023; son of longtime opposition leader Étienne Tshisekedi.",
    fullBiography:
      "Félix Antoine Tshisekedi Tshilombo became president in January 2019 following the 2018 election, in what was widely described as the country's first peaceful transfer of power since independence. He was re-elected in the December 2023 general election. He is the son of longtime opposition figure Étienne Tshisekedi.",
    birthDate: "1963-06-13",
    province: "Kinshasa",
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/9/92/F%C3%A9lix_Tshisekedi_-_2019_%28cropped%29.jpg",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:F%C3%A9lix_Tshisekedi_-_2019_(cropped).jpg",
    sourceName: "Photo: U.S. Department of State / Michael Gross, via Wikimedia Commons (public domain)",
    keywords: ["president", "head of state", "politics", "2018 election", "2023 election"],
    aliases: ["Félix Antoine Tshisekedi Tshilombo"],
    active: true,
    featured: true,
    verified: true,
  },
  {
    slug: "etienne-tshisekedi",
    name: "Étienne Tshisekedi",
    category: "Politics",
    subcategory: "Opposition Leader",
    shortDescription:
      "Longtime opposition leader and founder of the UDPS party; a central figure in DRC's pro-democracy movement for decades.",
    fullBiography:
      "Étienne Tshisekedi wa Mulumba was a founding figure of the Union for Democracy and Social Progress (UDPS) and one of the most prominent opposition voices against both the Mobutu government and later administrations, repeatedly imprisoned and placed under house arrest over his decades of activism. He died in February 2017, before his son Félix Tshisekedi became president in 2019.",
    birthDate: "1932-12-14",
    deathDate: "2017-02-01",
    province: "Kasai-Oriental",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/6/64/%C3%89tienne_Tshisekedi.jpg",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:%C3%89tienne_Tshisekedi.jpg",
    sourceName: "Photo: Giuseppe Dominici, via Wikimedia Commons (public domain)",
    keywords: ["opposition", "udps", "politics", "pro-democracy"],
    aliases: ["Étienne Tshisekedi wa Mulumba"],
    active: true,
    featured: false,
    verified: true,
  },
  {
    slug: "denis-mukwege",
    name: "Denis Mukwege",
    category: "Politics",
    subcategory: "Statesman / Human Rights",
    shortDescription:
      "Gynecologist and human rights advocate; 2018 Nobel Peace Prize laureate for his work treating survivors of sexual violence in conflict.",
    fullBiography:
      "Denis Mukwege founded Panzi Hospital in Bukavu, South Kivu, where he and his colleagues have treated tens of thousands of survivors of sexual violence connected to the region's conflicts. He was awarded the 2018 Nobel Peace Prize jointly with Nadia Murad for efforts to end the use of sexual violence as a weapon of war, and has remained an outspoken advocate and occasional political voice on the DRC's conflicts and governance.",
    birthDate: "1955-03-01",
    birthplace: "Bukavu, South Kivu",
    province: "South Kivu",
    city: "Bukavu",
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/0/0a/Denis_Mukwege_par_Claude_Truong-Ngoc_novembre_2014_%283x4_cropped%29.jpg",
    sourceUrl:
      "https://commons.wikimedia.org/wiki/File:Denis_Mukwege_par_Claude_Truong-Ngoc_novembre_2014_(3x4_cropped).jpg",
    sourceName: "Photo: Claude Truong-Ngoc, via Wikimedia Commons (CC BY-SA 3.0)",
    keywords: ["human rights", "nobel peace prize", "panzi hospital", "bukavu", "statesman"],
    aliases: [],
    active: true,
    featured: true,
    verified: true,
  },

  // ---- Politics: institutions. No portrait photos apply; images left
  // blank (falls back to the neutral placeholder) rather than using an
  // unverified logo/building photo.
  {
    slug: "ceni-drc",
    name: "Independent National Electoral Commission (CENI)",
    category: "Politics",
    subcategory: "Institution",
    shortDescription:
      "The body responsible for organizing and overseeing elections in the DRC.",
    keywords: ["ceni", "elections", "institution", "electoral commission"],
    aliases: ["CENI", "Commission Électorale Nationale Indépendante"],
    active: true,
    featured: false,
    verified: true,
  },
  {
    slug: "parliament-of-the-drc",
    name: "Parliament of the DRC",
    category: "Politics",
    subcategory: "Institution",
    shortDescription:
      "The DRC's bicameral legislature, composed of the National Assembly and the Senate.",
    keywords: ["parliament", "national assembly", "senate", "institution", "legislature"],
    aliases: ["Parlement de la RDC"],
    active: true,
    featured: false,
    verified: true,
  },
  {
    slug: "presidency-of-the-drc",
    name: "Presidency of the DRC",
    category: "Politics",
    subcategory: "Institution",
    shortDescription:
      "The executive office of the head of state of the Democratic Republic of the Congo.",
    keywords: ["presidency", "executive", "institution", "head of state"],
    aliases: ["Présidence de la RDC"],
    active: true,
    featured: false,
    verified: true,
  },
  {
    slug: "constitutional-court-drc",
    name: "Constitutional Court",
    category: "Politics",
    subcategory: "Institution",
    shortDescription:
      "The DRC's highest court for constitutional matters, established under the 2006 Constitution.",
    keywords: ["constitutional court", "judiciary", "institution", "constitution"],
    aliases: ["Cour Constitutionnelle"],
    active: true,
    featured: false,
    verified: true,
  },

  // ---- Politics: historical events and milestones. Dates/summaries kept
  // to widely-documented facts; no images sourced for these (lower
  // priority than portraits — falls back to the placeholder).
  {
    slug: "independence-1960",
    name: "Independence (1960)",
    category: "Politics",
    subcategory: "Historical Event",
    shortDescription:
      "The Democratic Republic of the Congo declared independence from Belgium on June 30, 1960.",
    publishedDate: "1960-06-30",
    keywords: ["independence", "1960", "belgium", "history"],
    aliases: ["Congolese independence", "30 June 1960"],
    active: true,
    featured: true,
    verified: true,
  },
  {
    slug: "congo-crisis",
    name: "Congo Crisis",
    category: "Politics",
    subcategory: "Historical Event",
    shortDescription:
      "A period of political upheaval from 1960 to 1965 following independence, including the Katanga and South Kasai secessions and UN intervention.",
    keywords: ["congo crisis", "katanga", "secession", "history", "1960s"],
    aliases: [],
    active: true,
    featured: false,
    verified: true,
  },
  {
    slug: "first-congo-war",
    name: "First Congo War",
    category: "Politics",
    subcategory: "Historical Event",
    shortDescription:
      "A 1996–1997 conflict that toppled Mobutu Sese Seko and brought Laurent-Désiré Kabila to power.",
    keywords: ["first congo war", "1996", "1997", "mobutu", "kabila", "history"],
    aliases: [],
    active: true,
    featured: false,
    verified: true,
  },
  {
    slug: "second-congo-war",
    name: "Second Congo War",
    category: "Politics",
    subcategory: "Historical Event",
    shortDescription:
      "A 1998–2003 multi-national conflict involving several African states, among the deadliest conflicts since World War II.",
    keywords: ["second congo war", "1998", "2003", "history", "conflict"],
    aliases: ["Africa's World War"],
    active: true,
    featured: false,
    verified: true,
  },
  {
    slug: "2006-elections",
    name: "2006 Elections",
    category: "Politics",
    subcategory: "Election",
    shortDescription:
      "The DRC's first multi-party elections since independence, held under the newly adopted 2006 Constitution; won by Joseph Kabila.",
    publishedDate: "2006-10-29",
    keywords: ["2006 elections", "joseph kabila", "election", "history"],
    aliases: [],
    active: true,
    featured: false,
    verified: true,
  },
  {
    slug: "2018-elections",
    name: "2018 Elections",
    category: "Politics",
    subcategory: "Election",
    shortDescription:
      "The election that brought Félix Tshisekedi to power, widely described as the DRC's first peaceful transfer of power since independence.",
    publishedDate: "2018-12-30",
    keywords: ["2018 elections", "felix tshisekedi", "election", "history"],
    aliases: [],
    active: true,
    featured: false,
    verified: true,
  },
  {
    slug: "2023-elections",
    name: "2023 Elections",
    category: "Politics",
    subcategory: "Election",
    shortDescription:
      "The general election in which Félix Tshisekedi was re-elected to a second term.",
    publishedDate: "2023-12-20",
    keywords: ["2023 elections", "felix tshisekedi", "election"],
    aliases: [],
    active: true,
    featured: false,
    verified: true,
  },
  {
    slug: "global-and-all-inclusive-agreement",
    name: "Global and All-Inclusive Agreement (2002)",
    category: "Politics",
    subcategory: "Peace Agreement",
    shortDescription:
      "The Pretoria/Sun City peace accord that formally ended the Second Congo War and established a transitional government.",
    publishedDate: "2002-12-17",
    keywords: ["peace agreement", "sun city", "pretoria", "transitional government", "2002"],
    aliases: ["Sun City Agreement", "Pretoria Accord"],
    active: true,
    featured: false,
    verified: true,
  },
  {
    slug: "2006-constitution",
    name: "2006 Constitution",
    category: "Politics",
    subcategory: "Constitutional Milestone",
    shortDescription:
      "The DRC's current constitution, adopted by referendum in December 2005 and promulgated in February 2006.",
    publishedDate: "2006-02-18",
    keywords: ["constitution", "2006", "referendum", "constitutional milestone"],
    aliases: [],
    active: true,
    featured: false,
    verified: true,
  },
];

export default SEED_ITEMS;
