// The original 8 hardcoded gallery items, reshaped for congoGalleryItems.
// Used only by the one-time admin "seed" action in CongoGallery.jsx —
// not read anywhere else at runtime. Nothing here is deleted or replaced
// by later phases; new items get their own seed/entry, these stay put.
const SEED_ITEMS = [
  {
    slug: "fally-ipupa",
    name: "Fally Ipupa",
    category: "Music",
    shortDescription:
      "A modern Congolese music icon who brought Congolese sound to the world.",
    localImageKey: "fally-ipupa",
    keywords: ["musician", "singer", "rumba"],
    aliases: ["Fally"],
    active: true,
    featured: true,
    verified: true,
  },
  {
    slug: "koffi-olomide",
    name: "Koffi Olomidé",
    category: "Music",
    shortDescription:
      "One of the major voices of Congolese rumba and African music.",
    localImageKey: "koffi-olomide",
    keywords: ["musician", "rumba"],
    aliases: ["Koffi"],
    active: true,
    featured: false,
    verified: true,
  },
  {
    slug: "franco-luambo",
    name: "Franco Luambo",
    category: "Music",
    shortDescription:
      "A legendary figure whose music helped shape Congolese identity.",
    localImageKey: "franco-luambo",
    keywords: ["musician", "rumba", "tpok jazz"],
    aliases: ["Franco"],
    active: true,
    featured: false,
    verified: true,
  },
  {
    slug: "joseph-kabila",
    name: "Joseph Kabila",
    category: "Politics",
    subcategory: "Head of State",
    shortDescription:
      "President of the DRC from 2001 to 2019, succeeding his father Laurent-Désiré Kabila after his assassination.",
    fullBiography:
      "Joseph Kabila became president in January 2001 following the assassination of his father, Laurent-Désiré Kabila, initially as the country's youngest head of state. His presidency spanned the end of the Second Congo War, the 2006 and 2011 elections, and a prolonged period (2016–2019) in which he remained in office past the end of his constitutional mandate before the 2018 election. He was succeeded by Félix Tshisekedi in January 2019.",
    birthDate: "1971-06-04",
    birthplace: "Fizi, South Kivu",
    province: "South Kivu",
    localImageKey: "joseph-kabila",
    keywords: ["president", "politics", "head of state", "kabila"],
    aliases: [],
    active: true,
    featured: true,
    verified: true,
  },
  {
    slug: "kinshasa",
    name: "Kinshasa",
    category: "Cities",
    province: "Kinshasa",
    country: "DR Congo",
    shortDescription:
      "The capital city, full of energy, music, politics, creativity, and movement.",
    localImageKey: "kinshasa",
    keywords: ["capital", "city"],
    active: true,
    featured: true,
    verified: true,
  },
  {
    slug: "boulevard-du-30-juin",
    name: "Boulevard du 30 Juin",
    category: "Cities",
    city: "Kinshasa",
    country: "DR Congo",
    shortDescription:
      "One of Kinshasa’s most symbolic roads, representing movement and national life.",
    localImageKey: "boulevard-du-30-juin",
    keywords: ["boulevard", "30 juin", "kinshasa"],
    active: true,
    featured: false,
    verified: true,
  },
  {
    slug: "eastern-congo",
    name: "Eastern Congo",
    category: "History",
    subcategory: "Memory & Crisis",
    shortDescription:
      "A place of pain, resilience, and courage. Congo Unity remembers the East.",
    fullBiography:
      "Eastern Congo — principally North Kivu, South Kivu, and Ituri — has experienced recurring armed conflict since the First and Second Congo Wars, driven by a mix of regional politics, control over mineral resources, and armed groups including remnants of the forces behind the 1994 Rwandan genocide and, more recently, the M23 rebel movement. Millions have been displaced over the past three decades, and the region remains the subject of ongoing UN peacekeeping (MONUSCO) and humanitarian efforts.",
    localImageKey: "eastern-congo",
    sourceName: "Wikipedia: Kivu conflict",
    sourceUrl: "https://en.wikipedia.org/wiki/Kivu_conflict",
    keywords: ["crisis", "kivu", "memory", "m23", "conflict"],
    aliases: [],
    active: true,
    featured: false,
    verified: true,
  },
  {
    slug: "flag-of-the-drc",
    name: "Flag of the DRC",
    category: "Culture",
    subcategory: "National Symbol",
    shortDescription:
      "The flag reminds us that we are one people, even when everything tries to divide us.",
    localImageKey: "flag-of-the-drc",
    keywords: ["flag", "symbol", "national"],
    active: true,
    featured: true,
    verified: true,
  },

  // ---- Phase 2 additions below: no local photo exists for these 7, so
  // each uses a verified, freely-licensed image from Wikimedia Commons
  // instead (license + photographer checked individually, not assumed —
  // see sourceUrl/sourceName for attribution). Dates are only included
  // where a specific source confirmed them; left blank otherwise rather
  // than guessed.
  {
    slug: "werrason",
    name: "Werrason",
    category: "Music",
    subcategory: "Soukous / Ndombolo",
    shortDescription:
      "Congolese musician and bandleader of Wenge Musica Maison Mère, originally part of Wenge Musica; one of the leading soukous/ndombolo artists of the 1990s–2000s.",
    birthDate: "1965",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/8/8e/Werrason.jpg",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Werrason.jpg",
    sourceName: "Photo via Wikimedia Commons (CC BY-SA)",
    keywords: ["musician", "wenge musica", "soukous", "ndombolo"],
    aliases: [],
    active: true,
    featured: false,
    verified: true,
  },
  {
    slug: "papa-wemba",
    name: "Papa Wemba",
    category: "Music",
    subcategory: "Rumba Rock",
    shortDescription:
      "Congolese singer and a founding figure of \"Congolese rumba rock,\" closely associated with the Sape fashion movement; co-founded Zaiko Langa Langa before leading his own groups.",
    birthDate: "1949-06-14",
    deathDate: "2016-04-24",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/6/63/Papa_Wemba.jpg",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Papa_Wemba.jpg",
    sourceName: "Photo: Radio Okapi via Wikimedia Commons (CC BY 2.0)",
    keywords: ["musician", "zaiko langa langa", "sape", "rumba rock"],
    aliases: [],
    active: true,
    featured: false,
    verified: true,
  },
  {
    slug: "tabu-ley-rochereau",
    name: "Tabu Ley Rochereau",
    category: "Music",
    subcategory: "Rumba",
    shortDescription:
      "Legendary singer and bandleader (African Fiesta, later Afrisa International); one of the most important figures of Congolese rumba's golden era from the 1960s onward.",
    birthDate: "1940-11-13",
    deathDate: "2013-11-30",
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/6/66/Press_photo_of_Tabu_Ley_Rochereau_in_San_Francisco_%281980%29.jpg",
    sourceUrl:
      "https://commons.wikimedia.org/wiki/File:Press_photo_of_Tabu_Ley_Rochereau_in_San_Francisco_(1980).jpg",
    sourceName: "Photo: Philip Gould / The Rosebud Agency, via Wikimedia Commons (public domain)",
    keywords: ["musician", "african fiesta", "afrisa international", "rumba"],
    aliases: ["Rochereau"],
    active: true,
    featured: false,
    verified: true,
  },
  {
    slug: "tshala-muana",
    name: "Tshala Muana",
    category: "Music",
    subcategory: "Mutuashi",
    shortDescription:
      "Celebrated singer and dancer known as the \"Queen of Mutuashi,\" a traditional Congolese dance she helped popularize internationally; prominent from the 1980s.",
    birthDate: "1958-03-13",
    deathDate: "2022-12-10",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/8/8c/Tshala_muana_2015.jpg",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Tshala_muana_2015.jpg",
    sourceName: "Photo via Wikimedia Commons (CC BY-SA 4.0)",
    keywords: ["musician", "dancer", "mutuashi"],
    aliases: [],
    active: true,
    featured: false,
    verified: true,
  },
  {
    slug: "mbilia-bel",
    name: "Mbilia Bel",
    category: "Music",
    subcategory: "Rumba",
    shortDescription:
      "Congolese singer, one of the most prominent female voices in Congolese rumba; rose to fame performing with Tabu Ley Rochereau's Afrisa International in the 1980s before a solo career.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/a/ae/Mbilia_Bel%2C_Zaire.jpg",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Mbilia_Bel,_Zaire.jpg",
    sourceName: "Photo via Wikimedia Commons (public domain, CC0)",
    keywords: ["musician", "afrisa international", "rumba"],
    aliases: ["M'bilia Bel"],
    active: true,
    featured: false,
    verified: true,
  },
  {
    slug: "ferre-gola",
    name: "Ferre Gola",
    category: "Music",
    subcategory: "Rumba / Ndombolo",
    shortDescription:
      "Congolese singer and former member of Wenge Musica BCBG, known for his vocal range; a prominent rumba/ndombolo artist since the 2000s.",
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/f/f1/Ferr%C3%A9_Gola_2024_performance.jpg",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Ferr%C3%A9_Gola_2024_performance.jpg",
    sourceName: "Photo via Wikimedia Commons (CC BY 4.0)",
    keywords: ["musician", "wenge musica bcbg", "ndombolo"],
    aliases: ["Ferré Gola"],
    active: true,
    featured: false,
    verified: true,
  },
  {
    slug: "innossb",
    name: "Innoss'B",
    category: "Music",
    subcategory: "Afrobeat / Hip-Hop",
    shortDescription:
      "Contemporary Congolese singer, part of a newer generation blending Congolese rumba with Afrobeat and hip-hop influences.",
    birthDate: "1997-05-05",
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/6/67/Innoss%27B_%2821600557166%29.jpg",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Innoss'B_(21600557166).jpg",
    sourceName: "Photo: Abel Kavanagh / MONUSCO, via Wikimedia Commons (CC BY-SA 2.0)",
    keywords: ["musician", "rapper", "afrobeat"],
    aliases: ["Innoss B", "Innocent Balume"],
    active: true,
    featured: false,
    verified: true,
  },

  // ---- Politics: figures. Images verified individually on Wikimedia
  // Commons the same way as the Music section (license + author checked
  // per file, not assumed). Dates left blank where genuinely uncertain
  // in the historical record (e.g. Kasa-Vubu's exact birth date) rather
  // than guessed.
  {
    slug: "patrice-lumumba",
    name: "Patrice Lumumba",
    category: "Politics",
    subcategory: "Head of Government",
    shortDescription:
      "First Prime Minister of the independent Republic of the Congo in 1960; assassinated in 1961.",
    fullBiography:
      "Patrice Émery Lumumba led the independence movement that ended Belgian colonial rule and became the country's first Prime Minister when independence was declared on June 30, 1960. His government fell within months amid the Congo Crisis, and he was arrested, then killed in January 1961 in circumstances involving Congolese and Belgian actors that have been the subject of extensive historical investigation. He remains one of the most significant symbols of African independence.",
    birthDate: "1925-07-02",
    deathDate: "1961-01-17",
    birthplace: "Onalua, Kasai",
    province: "Kasai",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/d/d5/Patrice_Lumumba_official_portrait.jpg",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Patrice_Lumumba_official_portrait.jpg",
    sourceName: "Official 1960 government portrait, via Wikimedia Commons (public domain)",
    keywords: ["prime minister", "independence", "politics", "congo crisis"],
    aliases: ["Patrice Émery Lumumba"],
    active: true,
    featured: true,
    verified: true,
  },
  {
    slug: "joseph-kasa-vubu",
    name: "Joseph Kasa-Vubu",
    category: "Politics",
    subcategory: "Head of State",
    shortDescription:
      "First President of the independent Republic of the Congo, serving from 1960 to 1965.",
    fullBiography:
      "Joseph Kasa-Vubu was a founding leader of the ABAKO political party and became the country's first President at independence in June 1960. He remained in office through the turbulent Congo Crisis years until he was deposed in a 1965 coup led by Joseph-Désiré Mobutu.",
    deathDate: "1969-03-24",
    province: "Kongo Central",
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/f/ff/Joseph_Kasa-Vubu_in_1960_%28cropped%29.jpg",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Joseph_Kasa-Vubu_in_1960_(cropped).jpg",
    sourceName: "Photo: Anefo / Dutch National Archives, via Wikimedia Commons (CC0)",
    keywords: ["president", "independence", "abako", "politics"],
    aliases: [],
    active: true,
    featured: false,
    verified: true,
  },
  {
    slug: "mobutu-sese-seko",
    name: "Mobutu Sese Seko",
    category: "Politics",
    subcategory: "Head of State",
    shortDescription:
      "President from 1965 to 1997, ruling for over three decades after taking power in a coup and renaming the country Zaire.",
    fullBiography:
      "Joseph-Désiré Mobutu seized power in a 1965 coup and ruled for 32 years, renaming the country Zaire in 1971 and himself Mobutu Sese Seko. His long rule was marked by centralized one-party control and a personality cult, alongside widely documented corruption and human rights abuses. He was overthrown in 1997 during the First Congo War by forces led by Laurent-Désiré Kabila, and died in exile later that year.",
    birthDate: "1930-10-14",
    deathDate: "1997-09-07",
    birthplace: "Lisala, Équateur",
    province: "Équateur",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/7/7e/Mobutu_Sese_Seko%2C_1969.jpg",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Mobutu_Sese_Seko,_1969.jpg",
    sourceName: "Photo: © European Union, via Wikimedia Commons (attribution required)",
    keywords: ["president", "zaire", "coup", "politics", "dictator"],
    aliases: ["Joseph-Désiré Mobutu"],
    active: true,
    featured: true,
    verified: true,
  },
  {
    slug: "laurent-desire-kabila",
    name: "Laurent-Désiré Kabila",
    category: "Politics",
    subcategory: "Head of State",
    shortDescription:
      "President from 1997 to 2001, having led the rebellion that overthrew Mobutu in the First Congo War.",
    fullBiography:
      "Laurent-Désiré Kabila led the AFDL rebel coalition that overthrew Mobutu Sese Seko in 1997, becoming president and renaming Zaire back to the Democratic Republic of the Congo. His presidency was soon consumed by the outbreak of the Second Congo War in 1998. He was assassinated by a bodyguard in January 2001 and was succeeded by his son, Joseph Kabila.",
    birthDate: "1939-11-27",
    deathDate: "2001-01-16",
    birthplace: "Baudouinville (Moba), Tanganyika",
    province: "Tanganyika",
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/6/6d/Laurent_D%C3%A9sir%C3%A9_Kabila_portrait_3x4.jpg",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Laurent_D%C3%A9sir%C3%A9_Kabila_portrait_3x4.jpg",
    sourceName: "Photo: Etienne Scholasse / European Communities, via Wikimedia Commons (CC BY 4.0)",
    keywords: ["president", "afdl", "first congo war", "politics"],
    aliases: [],
    active: true,
    featured: false,
    verified: true,
  },
  {
    slug: "felix-tshisekedi",
    name: "Félix Tshisekedi",
    category: "Politics",
    subcategory: "Head of State",
    shortDescription:
      "President of the DRC since January 2019, re-elected in 2023; son of longtime opposition leader Étienne Tshisekedi.",
    fullBiography:
      "Félix Antoine Tshisekedi Tshilombo became president in January 2019 following the 2018 election, in what was widely described as the country's first peaceful transfer of power since independence. He was re-elected in the December 2023 general election. He is the son of longtime opposition figure Étienne Tshisekedi.",
    birthDate: "1963-06-13",
    province: "Kinshasa",
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/9/92/F%C3%A9lix_Tshisekedi_-_2019_%28cropped%29.jpg",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:F%C3%A9lix_Tshisekedi_-_2019_(cropped).jpg",
    sourceName: "Photo: U.S. Department of State / Michael Gross, via Wikimedia Commons (public domain)",
    keywords: ["president", "head of state", "politics", "2018 election", "2023 election"],
    aliases: ["Félix Antoine Tshisekedi Tshilombo"],
    active: true,
    featured: true,
    verified: true,
  },
  {
    slug: "etienne-tshisekedi",
    name: "Étienne Tshisekedi",
    category: "Politics",
    subcategory: "Opposition Leader",
    shortDescription:
      "Longtime opposition leader and founder of the UDPS party; a central figure in DRC's pro-democracy movement for decades.",
    fullBiography:
      "Étienne Tshisekedi wa Mulumba was a founding figure of the Union for Democracy and Social Progress (UDPS) and one of the most prominent opposition voices against both the Mobutu government and later administrations, repeatedly imprisoned and placed under house arrest over his decades of activism. He died in February 2017, before his son Félix Tshisekedi became president in 2019.",
    birthDate: "1932-12-14",
    deathDate: "2017-02-01",
    province: "Kasai-Oriental",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/6/64/%C3%89tienne_Tshisekedi.jpg",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:%C3%89tienne_Tshisekedi.jpg",
    sourceName: "Photo: Giuseppe Dominici, via Wikimedia Commons (public domain)",
    keywords: ["opposition", "udps", "politics", "pro-democracy"],
    aliases: ["Étienne Tshisekedi wa Mulumba"],
    active: true,
    featured: false,
    verified: true,
  },
  {
    slug: "denis-mukwege",
    name: "Denis Mukwege",
    category: "Politics",
    subcategory: "Statesman / Human Rights",
    shortDescription:
      "Gynecologist and human rights advocate; 2018 Nobel Peace Prize laureate for his work treating survivors of sexual violence in conflict.",
    fullBiography:
      "Denis Mukwege founded Panzi Hospital in Bukavu, South Kivu, where he and his colleagues have treated tens of thousands of survivors of sexual violence connected to the region's conflicts. He was awarded the 2018 Nobel Peace Prize jointly with Nadia Murad for efforts to end the use of sexual violence as a weapon of war, and has remained an outspoken advocate and occasional political voice on the DRC's conflicts and governance.",
    birthDate: "1955-03-01",
    birthplace: "Bukavu, South Kivu",
    province: "South Kivu",
    city: "Bukavu",
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/0/0a/Denis_Mukwege_par_Claude_Truong-Ngoc_novembre_2014_%283x4_cropped%29.jpg",
    sourceUrl:
      "https://commons.wikimedia.org/wiki/File:Denis_Mukwege_par_Claude_Truong-Ngoc_novembre_2014_(3x4_cropped).jpg",
    sourceName: "Photo: Claude Truong-Ngoc, via Wikimedia Commons (CC BY-SA 3.0)",
    keywords: ["human rights", "nobel peace prize", "panzi hospital", "bukavu", "statesman"],
    aliases: [],
    active: true,
    featured: true,
    verified: true,
  },

  // ---- Politics: institutions. No portrait photos apply; images left
  // blank (falls back to the neutral placeholder) rather than using an
  // unverified logo/building photo.
  {
    slug: "ceni-drc",
    name: "Independent National Electoral Commission (CENI)",
    category: "Politics",
    subcategory: "Institution",
    shortDescription:
      "The body responsible for organizing and overseeing elections in the DRC.",
    keywords: ["ceni", "elections", "institution", "electoral commission"],
    aliases: ["CENI", "Commission Électorale Nationale Indépendante"],
    active: true,
    featured: false,
    verified: true,
  },
  {
    slug: "parliament-of-the-drc",
    name: "Parliament of the DRC",
    category: "Politics",
    subcategory: "Institution",
    shortDescription:
      "The DRC's bicameral legislature, composed of the National Assembly and the Senate.",
    keywords: ["parliament", "national assembly", "senate", "institution", "legislature"],
    aliases: ["Parlement de la RDC"],
    active: true,
    featured: false,
    verified: true,
  },
  {
    slug: "presidency-of-the-drc",
    name: "Presidency of the DRC",
    category: "Politics",
    subcategory: "Institution",
    shortDescription:
      "The executive office of the head of state of the Democratic Republic of the Congo.",
    keywords: ["presidency", "executive", "institution", "head of state"],
    aliases: ["Présidence de la RDC"],
    active: true,
    featured: false,
    verified: true,
  },
  {
    slug: "constitutional-court-drc",
    name: "Constitutional Court",
    category: "Politics",
    subcategory: "Institution",
    shortDescription:
      "The DRC's highest court for constitutional matters, established under the 2006 Constitution.",
    keywords: ["constitutional court", "judiciary", "institution", "constitution"],
    aliases: ["Cour Constitutionnelle"],
    active: true,
    featured: false,
    verified: true,
  },

  // ---- Politics: elections. The independence/crisis/wars/agreement/
  // constitution entries that used to live here moved to the History
  // category below — they're historical narrative, not the ongoing
  // political process these election entries describe.
  {
    slug: "2006-elections",
    name: "2006 Elections",
    category: "Politics",
    subcategory: "Election",
    shortDescription:
      "The DRC's first multi-party elections since independence, held under the newly adopted 2006 Constitution; won by Joseph Kabila.",
    publishedDate: "2006-10-29",
    keywords: ["2006 elections", "joseph kabila", "election", "history"],
    aliases: [],
    active: true,
    featured: false,
    verified: true,
  },
  {
    slug: "2018-elections",
    name: "2018 Elections",
    category: "Politics",
    subcategory: "Election",
    shortDescription:
      "The election that brought Félix Tshisekedi to power, widely described as the DRC's first peaceful transfer of power since independence.",
    publishedDate: "2018-12-30",
    keywords: ["2018 elections", "felix tshisekedi", "election", "history"],
    aliases: [],
    active: true,
    featured: false,
    verified: true,
  },
  {
    slug: "2023-elections",
    name: "2023 Elections",
    category: "Politics",
    subcategory: "Election",
    shortDescription:
      "The general election in which Félix Tshisekedi was re-elected to a second term.",
    publishedDate: "2023-12-20",
    keywords: ["2023 elections", "felix tshisekedi", "election"],
    aliases: [],
    active: true,
    featured: false,
    verified: true,
  },

  // ---- History: eras, wars, agreements, constitutional milestones, and
  // maps. Every item here carries sourceName/sourceUrl per the History
  // spec, written in neutral, factual language. Images are used only
  // where a specific file's license was verified on its own Commons
  // page; left blank otherwise rather than guessing at rights.
  {
    slug: "pre-colonial-congo",
    name: "Pre-Colonial Congo: Kingdoms and Societies",
    category: "History",
    subcategory: "Historical Era",
    shortDescription:
      "Before European colonization, the Congo region was home to organized kingdoms, chiefdoms, and trading societies, including the Kongo, Luba, and Lunda.",
    fullBiography:
      "Long before the Berlin Conference and Leopold II's Congo Free State, the territory of the modern DRC held a range of organized societies — from centralized kingdoms such as Kongo (west), and Luba and Lunda (center and east), to smaller chiefdoms and decentralized communities across the Congo Basin. Bantu-speaking peoples migrated into the region beginning roughly 2000 BCE, gradually developing agriculture, ironworking, and long-distance trade networks in goods such as copper and salt. These societies developed their own systems of governance and law, and many of their cultural and artistic traditions continue to shape Congolese identity today.",
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/e/e7/African-civilizations-map-pre-colonial.svg",
    sourceUrl: "https://en.wikipedia.org/wiki/Pre-colonial_history_of_the_Democratic_Republic_of_the_Congo",
    sourceName: "Wikipedia: Pre-colonial history of the Democratic Republic of the Congo",
    keywords: ["pre-colonial", "kingdoms", "bantu", "history", "kongo", "luba", "lunda"],
    aliases: [],
    active: true,
    featured: true,
    verified: true,
  },
  {
    slug: "kingdom-of-kongo",
    name: "Kingdom of Kongo",
    category: "History",
    subcategory: "Historical Era",
    shortDescription:
      "A centralized West-Central African kingdom founded around 1390, spanning parts of the modern DRC, Angola, Congo-Brazzaville, and Gabon.",
    fullBiography:
      "The Kingdom of Kongo was founded around 1390 near the mouth of the Congo River, with its capital at Mbanza Kongo (in present-day Angola). At its height it stretched from the Atlantic coast to the Kwango River, encompassing parts of what are now the DRC, Angola, the Republic of Congo, and Gabon, and featured a centralized monarchy, provincial administration, and a shell-currency system. Portuguese explorers reached Kongo in 1483, and the kingdom's ruling elite converted to Christianity in 1491, beginning a long and often fraught relationship with Portugal. Civil war from 1665 and gradual fragmentation weakened central authority over the following two centuries; Kongo became a Portuguese vassal state in 1857, and Portugal formally abolished the titular monarchy in 1914.",
    publishedDate: "1390-01-01",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/0/01/Kingdom_of_Kongo_1600.png",
    sourceUrl: "https://en.wikipedia.org/wiki/Kingdom_of_Kongo",
    sourceName: "Map: Jarle Grøhn, via Wikimedia Commons (CC BY 3.0); Wikipedia: Kingdom of Kongo",
    keywords: ["kingdom of kongo", "mbanza kongo", "pre-colonial", "history"],
    aliases: ["Kongo Kingdom"],
    active: true,
    featured: true,
    verified: true,
  },
  {
    slug: "luba-kingdom",
    name: "Luba Kingdom",
    category: "History",
    subcategory: "Historical Era",
    shortDescription:
      "A pre-colonial kingdom centered in the Upemba Depression of southern DRC, ruled by a sacred king known as the Mulopwe.",
    fullBiography:
      "The Luba Kingdom arose in the marshy grasslands of the Upemba Depression in what is now southern DRC; historians disagree on the exact founding period, with estimates ranging from as early as the 8th century to shortly before the 15th. It was led by a sacred king, the Mulopwe, supported by court nobles (Bamfumu) and regional clan kings (Balopwe), with the Bambudye society preserving the kingdom's oral history and traditions across the realm. The kingdom weakened in the late 19th century as long-distance trade networks were disrupted by East African traders seeking slaves and ivory, and collapsed in 1889 following a succession dispute, after which its territory was absorbed into the Congo Free State.",
    sourceUrl: "https://en.wikipedia.org/wiki/Luba_Kingdom",
    sourceName: "Wikipedia: Luba Kingdom",
    keywords: ["luba kingdom", "mulopwe", "upemba", "pre-colonial", "history"],
    aliases: ["Luba Empire"],
    active: true,
    featured: false,
    verified: true,
  },
  {
    slug: "lunda-empire",
    name: "Lunda Empire",
    category: "History",
    subcategory: "Historical Era",
    shortDescription:
      "A pre-colonial empire centered in what is now Katanga, ruled by a paramount king known as the Mwata Yamvo, at its height covering around 300,000 km².",
    fullBiography:
      "The Lunda Empire was established in the 17th century, with its central state in what is now Katanga Province, and grew through a system of tributary chieftainships that retained local autonomy in exchange for allegiance to a paramount ruler, the Mwata Yamvo, under a tradition of \"perpetual kingship\" in which successors adopted their predecessors' titles and roles. At its 19th-century height, the empire's influence extended across roughly 300,000 km² spanning parts of the modern DRC, Angola, and Zambia. It collapsed after invasions by Chokwe forces armed with firearms in the late 19th century, and by 1887 its former territory had been divided among Portuguese Angola, the Congo Free State, and British-administered Northern Rhodesia.",
    publishedDate: "1665-01-01",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/f/fb/Lunda_Empire.png",
    sourceUrl: "https://en.wikipedia.org/wiki/Lunda_Empire",
    sourceName: "Map: U.S. Library of Congress, via Wikimedia Commons (public domain); Wikipedia: Lunda Empire",
    keywords: ["lunda empire", "mwata yamvo", "katanga", "pre-colonial", "history"],
    aliases: ["Lunda Kingdom"],
    active: true,
    featured: false,
    verified: true,
  },
  {
    slug: "congo-free-state",
    name: "Congo Free State",
    category: "History",
    subcategory: "Historical Era",
    shortDescription:
      "A personal colony of Belgium's King Leopold II from 1885 to 1908, notorious for a forced-labor rubber economy and widespread atrocities.",
    fullBiography:
      "The Congo Free State was established on August 1, 1885, after the Berlin Conference recognized King Leopold II of Belgium as sovereign over the territory — not as a Belgian colony, but as his personal possession, administered from Brussels through appointed officials. Leopold's administration ran a forced-labor system built around rubber and ivory quotas, enforced by the Force Publique, which caused mass suffering, mutilation, and death across the territory. Estimates of the death toll vary widely among historians, from roughly one million to ten million, reflecting the difficulty of counting a population that was never systematically recorded. International exposure of the abuses — including Roger Casement's 1903 report and the advocacy of the Congo Reform Association — forced Leopold to relinquish personal control, and Belgium formally annexed the territory as the Belgian Congo on November 15, 1908.",
    publishedDate: "1885-08-01",
    sourceName: "Wikipedia: Congo Free State",
    sourceUrl: "https://en.wikipedia.org/wiki/Congo_Free_State",
    keywords: ["congo free state", "leopold ii", "history", "colonial era", "1885"],
    aliases: ["État indépendant du Congo", "Independent State of the Congo"],
    active: true,
    featured: true,
    verified: true,
  },
  {
    slug: "belgian-congo",
    name: "Belgian Congo",
    category: "History",
    subcategory: "Historical Era",
    shortDescription:
      "The formal Belgian colony that succeeded the Congo Free State, lasting from 1908 until independence in 1960.",
    fullBiography:
      "Belgium's parliament voted to annex the Congo Free State on October 18, 1908, with the annexation taking formal effect on November 15, 1908, ending Leopold II's personal rule. As a state colony, the Belgian Congo was organized into provinces, districts, and territories under a Governor-General, with local indigenous courts operating under colonial oversight. The territory supplied significant raw materials during both World Wars, including uranium used in the Manhattan Project during World War II. Colonial rule continued, with limited political participation introduced only shortly before independence — the first municipal elections open to Black voters were held in 1957 — until the Belgian Congo became independent as the Republic of the Congo on June 30, 1960.",
    publishedDate: "1908-11-15",
    sourceName: "Wikipedia: Belgian Congo",
    sourceUrl: "https://en.wikipedia.org/wiki/Belgian_Congo",
    keywords: ["belgian congo", "colonial era", "history", "1908", "1960"],
    aliases: ["Congo Belge"],
    active: true,
    featured: true,
    verified: true,
  },
  {
    slug: "independence-1960",
    name: "Independence (1960)",
    category: "History",
    subcategory: "Historical Event",
    shortDescription:
      "The Democratic Republic of the Congo declared independence from Belgium on June 30, 1960.",
    fullBiography:
      "Independence was granted on June 30, 1960, following a Round Table Conference held in Brussels earlier that year, in which Belgium agreed to a rapid transfer of power after growing nationalist unrest in the colony. Joseph Kasa-Vubu became the country's first president and Patrice Lumumba its first prime minister. The new state, initially named the Republic of the Congo, had almost no Congolese-trained administrators, army officers, or professionals at independence — a legacy of Belgian colonial policy — which contributed directly to the instability of the Congo Crisis that followed within days.",
    publishedDate: "1960-06-30",
    sourceName: "Wikipedia: Belgian Congo",
    sourceUrl: "https://en.wikipedia.org/wiki/Belgian_Congo",
    keywords: ["independence", "1960", "belgium", "history"],
    aliases: ["Congolese independence", "30 June 1960"],
    active: true,
    featured: true,
    verified: true,
  },
  {
    slug: "congo-crisis",
    name: "Congo Crisis",
    category: "History",
    subcategory: "Historical Event",
    shortDescription:
      "A period of political upheaval from 1960 to 1965 following independence, including the Katanga and South Kasai secessions and UN intervention.",
    fullBiography:
      "Days after independence, a mutiny in the Force Publique triggered a broader breakdown of order. Katanga, led by Moïse Tshombe, and South Kasai seceded shortly afterward, and the United Nations deployed a peacekeeping mission (ONUC) to help stabilize the country. Prime Minister Patrice Lumumba was dismissed by President Kasa-Vubu in a constitutional standoff, later captured and killed in January 1961. Colonel Joseph-Désiré Mobutu seized power in a first coup in 1960 and again, definitively, in 1965, ending the crisis period.",
    publishedDate: "1960-07-05",
    sourceName: "Wikipedia: Congo Crisis",
    sourceUrl: "https://en.wikipedia.org/wiki/Congo_Crisis",
    keywords: ["congo crisis", "katanga", "secession", "history", "1960s"],
    aliases: [],
    active: true,
    featured: false,
    verified: true,
  },
  {
    slug: "zaire-era",
    name: "Zaire Era",
    category: "History",
    subcategory: "Historical Era",
    shortDescription:
      "The 1971–1997 period under President Mobutu Sese Seko, during which the country was renamed Zaire as part of his authenticité program.",
    fullBiography:
      "On October 27, 1971, President Mobutu Sese Seko renamed the country Zaire as part of a broader authenticité policy intended to move away from colonial-era names and symbols — cities were renamed (Léopoldville became Kinshasa), citizens were required to adopt African names, and Western dress was officially discouraged in favor of the abacost. Politically, the era was defined by one-party rule under Mobutu's Popular Movement of the Revolution, with power concentrated in the presidency. The economy declined sharply over the period amid mismanagement and widespread corruption. The Zaire era ended as Mobutu fled the country on May 17, 1997, during the First Congo War; the new government under Laurent-Désiré Kabila restored the name Democratic Republic of the Congo on May 21, 1997.",
    publishedDate: "1971-10-27",
    sourceName: "Wikipedia: Zaire",
    sourceUrl: "https://en.wikipedia.org/wiki/Zaire",
    keywords: ["zaire", "mobutu", "authenticite", "history", "1971", "1997"],
    aliases: ["Mobutu era"],
    active: true,
    featured: true,
    verified: true,
  },
  {
    slug: "zairianization",
    name: "Zaireanization",
    category: "History",
    subcategory: "Historical Event",
    shortDescription:
      "A 1973–1974 economic policy under Mobutu Sese Seko that nationalized foreign-owned businesses and redistributed them to Zairian nationals.",
    fullBiography:
      "On November 30, 1973, Mobutu Sese Seko announced the nationalization of foreign-owned plantations, ranches, and commercial businesses as an economic extension of his authenticité policy. Ownership was transferred to roughly 300 politically connected Zairians — mostly senior party and government officials — with smaller enterprises allocated to local notables. Many new owners lacked business experience and rapidly liquidated inventories for short-term profit, causing severe shortages of food, textiles, and medicine and driving prices sharply higher. By 1977, the resulting economic collapse forced Mobutu to begin reversing the policy (a process known as \"retrocession\") and to court foreign investors back to the country.",
    publishedDate: "1973-11-30",
    sourceName: "Wikipedia: Authenticité (Zaire)",
    sourceUrl: "https://en.wikipedia.org/wiki/Zairianization",
    keywords: ["zaireanization", "zairianization", "mobutu", "nationalization", "economy", "history"],
    aliases: ["Zairianization"],
    active: true,
    featured: false,
    verified: true,
  },
  {
    slug: "first-congo-war",
    name: "First Congo War",
    category: "History",
    subcategory: "Historical Event",
    shortDescription:
      "A 1996–1997 conflict that toppled Mobutu Sese Seko and brought Laurent-Désiré Kabila to power.",
    fullBiography:
      "The war began in October 1996 when the Alliance of Democratic Forces for the Liberation of Congo-Zaire (AFDL), led by Laurent-Désiré Kabila and backed by Rwanda and Uganda, launched an offensive from the east, initially targeting Hutu militias and refugee camps in the aftermath of the 1994 Rwandan genocide. Facing a collapsing and demoralized army, Mobutu Sese Seko's government fell in a matter of months; Kabila's forces took Kinshasa on May 17, 1997, and Kabila declared himself president, renaming Zaire the Democratic Republic of the Congo.",
    sourceName: "Wikipedia: First Congo War",
    sourceUrl: "https://en.wikipedia.org/wiki/First_Congo_War",
    keywords: ["first congo war", "1996", "1997", "mobutu", "kabila", "history"],
    aliases: [],
    active: true,
    featured: false,
    verified: true,
  },
  {
    slug: "second-congo-war",
    name: "Second Congo War",
    category: "History",
    subcategory: "Historical Event",
    shortDescription:
      "A 1998–2003 multi-national conflict involving several African states, among the deadliest conflicts since World War II.",
    fullBiography:
      "War broke out in August 1998 after President Laurent-Désiré Kabila moved to expel the Rwandan and Ugandan forces that had helped bring him to power the previous year, prompting a new rebellion backed by Rwanda and Uganda. At its height, the war drew in the armed forces of at least six other African nations, either supporting Kabila's government (including Zimbabwe, Angola, and Namibia) or the rebel factions. A 1999 Lusaka Ceasefire Agreement failed to fully halt the fighting. Estimates of the war's toll vary widely, but it is often cited as the deadliest conflict since World War II, with millions of deaths attributed mostly to disease and malnutrition amid the collapse of health and food systems. The war formally ended with the 2002 Global and All-Inclusive Agreement, though armed conflict has continued intermittently in the eastern DRC since.",
    sourceName: "Wikipedia: Second Congo War",
    sourceUrl: "https://en.wikipedia.org/wiki/Second_Congo_War",
    keywords: ["second congo war", "1998", "2003", "history", "conflict"],
    aliases: ["Africa's World War"],
    active: true,
    featured: false,
    verified: true,
  },
  {
    slug: "inter-congolese-dialogue",
    name: "Inter-Congolese Dialogue",
    category: "History",
    subcategory: "Historical Event",
    shortDescription:
      "The 2001–2002 peace negotiation process among the DRC's warring parties, facilitated by former Botswana president Ketumile Masire, that produced the agreements ending the Second Congo War.",
    fullBiography:
      "The Inter-Congolese Dialogue officially opened in Addis Ababa on October 15, 2001, facilitated by former Botswana president Sir Ketumile Masire under a mandate from the Organisation of African Unity. It brought together the DRC government, the Rwandan-backed RCD-Goma and Ugandan-backed MLC rebel movements, and unarmed opposition and civil-society groups. Talks continued at Sun City, South Africa, from February 25 to April 12, 2002, producing the partial Sun City Agreement, and negotiations concluded later that year with the more comprehensive Global and All-Inclusive Agreement.",
    publishedDate: "2001-10-15",
    sourceName: "Wikipedia: Sun City Agreement",
    sourceUrl: "https://en.wikipedia.org/wiki/Sun_City_Agreement",
    keywords: ["inter-congolese dialogue", "ketumile masire", "peace process", "history"],
    aliases: ["ICD"],
    active: true,
    featured: false,
    verified: true,
  },
  {
    slug: "global-and-all-inclusive-agreement",
    name: "Global and All-Inclusive Agreement (2002)",
    category: "History",
    subcategory: "Peace Agreement",
    shortDescription:
      "The December 2002 peace accord that formally ended the Second Congo War and established a transitional government, building on the earlier Sun City Agreement.",
    fullBiography:
      "As the Second Congo War wound down, delegates to the Inter-Congolese Dialogue signed the Sun City Agreement on April 2, 2002 — a partial accord that most, but not all, of the warring parties endorsed. Negotiations continued under UN mediation, and on December 16–17, 2002, the parties signed the more comprehensive Global and All-Inclusive Agreement on the Transition in the DRC, formally ending the war and setting up a power-sharing transitional government that led to the 2006 elections.",
    publishedDate: "2002-12-17",
    sourceName: "Wikipedia: Sun City Agreement",
    sourceUrl: "https://en.wikipedia.org/wiki/Sun_City_Agreement",
    keywords: ["peace agreement", "sun city", "transitional government", "2002"],
    aliases: ["Sun City Agreement", "Pretoria Accord"],
    active: true,
    featured: false,
    verified: true,
  },
  {
    slug: "transitional-government",
    name: "Transitional Government of the DRC (2003–2006)",
    category: "History",
    subcategory: "Historical Era",
    shortDescription:
      "The power-sharing \"1+4\" government established by the Global and All-Inclusive Agreement, which governed the DRC until the 2006 elections.",
    fullBiography:
      "The transitional government took office under a formula known as \"1+4\": Joseph Kabila was sworn in as transitional president on April 7, 2003, alongside four vice presidents representing the former belligerents and the unarmed opposition — Abdoulaye Yerodia Ndombasi for Kabila's government, Jean-Pierre Bemba for the MLC, Azarias Ruberwa for the RCD-Goma, and Arthur Z'Ahidi Ngoma for the political opposition — who took office on July 17, 2003. The transitional period oversaw the drafting and adoption of the 2006 Constitution and ended with the completion of the 2006 general election, when Kabila was sworn in as elected president on December 6, 2006.",
    publishedDate: "2003-04-07",
    sourceName: "Wikipedia: Transitional Government of the Democratic Republic of the Congo",
    sourceUrl: "https://en.wikipedia.org/wiki/Transitional_Government_of_the_Democratic_Republic_of_the_Congo",
    keywords: ["transitional government", "1+4", "power-sharing", "history"],
    aliases: ["1+4 government"],
    active: true,
    featured: false,
    verified: true,
  },
  {
    slug: "2006-constitution",
    name: "2006 Constitution",
    category: "History",
    subcategory: "Constitutional Milestone",
    shortDescription:
      "The DRC's current constitution, adopted by referendum in December 2005 and promulgated in February 2006.",
    fullBiography:
      "Drafted during the 2003–2006 transitional period established by the Global and All-Inclusive Agreement, the constitution was approved by popular referendum in December 2005 and promulgated by transitional president Joseph Kabila on February 18, 2006. It is the DRC's sixth constitution since 1960, and the first adopted directly by popular vote. It established a decentralized semi-presidential republic with a separation of powers among the executive, legislature, and judiciary, and divided the country into provinces with defined central and provincial authority.",
    publishedDate: "2006-02-18",
    sourceName: "Wikipedia: Constitution of the Democratic Republic of the Congo",
    sourceUrl: "https://en.wikipedia.org/wiki/Constitution_of_the_Democratic_Republic_of_the_Congo",
    keywords: ["constitution", "2006", "referendum", "constitutional milestone"],
    aliases: [],
    active: true,
    featured: false,
    verified: true,
  },
  {
    slug: "first-peaceful-transfer-of-power",
    name: "First Peaceful Transfer of Power (2019)",
    category: "History",
    subcategory: "National Milestone",
    shortDescription:
      "Félix Tshisekedi's January 2019 inauguration was widely described as the DRC's first peaceful transfer of presidential power since independence.",
    fullBiography:
      "Following the December 30, 2018 general election, Félix Tshisekedi was declared the winner and sworn in as president on January 24, 2019, succeeding Joseph Kabila. The transition was widely described in DRC and abroad as the country's first peaceful transfer of power between an outgoing and an incoming president since independence in 1960. The result was disputed, however: runner-up Martin Fayulu alleged the vote had been manipulated in Tshisekedi's favor and challenged it before the Constitutional Court, and independent observers including the Catholic Church's election-monitoring mission also raised doubts about the official count.",
    publishedDate: "2019-01-24",
    sourceName: "Wikipedia: 2018 Democratic Republic of the Congo general election",
    sourceUrl: "https://en.wikipedia.org/wiki/2018_Democratic_Republic_of_the_Congo_general_election",
    keywords: ["peaceful transfer of power", "2019", "tshisekedi", "national milestone", "history"],
    aliases: [],
    active: true,
    featured: true,
    verified: true,
  },
  {
    slug: "name-changes-of-the-congo",
    name: "Name Changes of the Congo",
    category: "History",
    subcategory: "National Milestone",
    shortDescription:
      "The country has carried five official names since 1885, each marking a distinct political era.",
    fullBiography:
      "The territory has been renamed five times: the Congo Free State (1885–1908), the Belgian Congo (1908–1960), the Republic of the Congo at independence in 1960 (often called Congo-Léopoldville to distinguish it from the neighboring Republic of the Congo), the Democratic Republic of the Congo from August 1964 under the Luluabourg Constitution, Zaire from October 27, 1971 under Mobutu Sese Seko's authenticité program, and back to the Democratic Republic of the Congo from May 21, 1997 under Laurent-Désiré Kabila.",
    sourceName: "Britannica: Why did DR Congo change its name?",
    sourceUrl: "https://www.britannica.com/question/Why-did-DR-Congo-change-its-name",
    keywords: ["name change", "zaire", "congo-leopoldville", "national milestone", "history"],
    aliases: [],
    active: true,
    featured: false,
    verified: true,
  },

  // ---- History: maps. Only Commons files with a clearly verified,
  // individually-checked license were used.
  {
    slug: "map-congo-free-state-1896",
    name: "1896 Map of the Congo Free State",
    category: "History",
    subcategory: "Historic Map",
    shortDescription:
      "A cartographic map of the Congo Free State published in 1896 by Léon de Moor, held by the Library of Congress.",
    fullBiography:
      "Published in 1896 by cartographer Léon de Moor for J. Lebègue & Co., this map depicts the Congo Free State roughly a decade before Belgium's 1908 annexation ended Leopold II's personal rule. It shows the territory's early administrative concession zones and settlements as recorded during that period, and is held today by the Library of Congress via the World Digital Library.",
    publishedDate: "1896-01-01",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/7/7e/Map_of_the_Belgian_Congo_WDL59.png",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Map_of_the_Belgian_Congo_WDL59.png",
    sourceName:
      "Map: Léon de Moor, published by J. Lebègue & Co. (1896) — Library of Congress / World Digital Library, via Wikimedia Commons (public domain)",
    keywords: ["map", "congo free state", "1896", "historic map", "cartography"],
    aliases: [],
    active: true,
    featured: false,
    verified: true,
  },
  {
    slug: "map-drc-provinces",
    name: "Map of the DRC's Provinces",
    category: "History",
    subcategory: "Historic Map",
    shortDescription:
      "A reference map showing the Democratic Republic of the Congo's present-day borders and administrative divisions.",
    fullBiography:
      "This modern reference map shows the DRC's current national borders, useful for orienting the country's 26 provinces (following the 2015 territorial reorganization) against the historical eras, cities, and events documented elsewhere in this gallery.",
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/1/1b/Democratic_Republic_of_the_Congo_adm_location_map.svg",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Democratic_Republic_of_the_Congo_adm_location_map.svg",
    sourceName: "Map: NordNordWest, via Wikimedia Commons (CC BY-SA 3.0 DE)",
    keywords: ["map", "provinces", "administrative divisions", "cartography"],
    aliases: [],
    active: true,
    featured: false,
    verified: true,
  },

  // ---- Cities: major DRC cities beyond Kinshasa. No local photos exist
  // for these, so each uses a Commons image verified on its own file
  // page (license + author checked individually, same discipline as
  // Music/Politics/History).
  {
    slug: "lubumbashi",
    name: "Lubumbashi",
    category: "Cities",
    province: "Haut-Katanga",
    country: "DR Congo",
    shortDescription:
      "The DRC's second-largest city and mining capital, at the heart of the copper and cobalt belt in the southeast.",
    fullBiography:
      "Founded in 1910 as a base for regional mining, Lubumbashi is the capital of Haut-Katanga Province and the country's principal industrial and mining hub, home to many of the DRC's largest copper and cobalt companies. The DRC produces more than 3% of the world's copper and roughly half its cobalt, most of it from the Katanga region. Known as \"the capital of copper,\" the city is the transportation and commercial center for mineral products from nearby mining towns including Likasi and Kolwezi.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/8/8d/Lubumbashi-downtown-banner.jpg",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Lubumbashi-downtown-banner.jpg",
    sourceName: "Photo: Oasisk, via Wikimedia Commons (CC BY-SA 3.0)",
    keywords: ["lubumbashi", "katanga", "haut-katanga", "mining", "copper", "cobalt", "city"],
    aliases: ["Élisabethville"],
    active: true,
    featured: true,
    verified: true,
  },
  {
    slug: "goma",
    name: "Goma",
    category: "Cities",
    province: "North Kivu",
    country: "DR Congo",
    shortDescription:
      "The capital of North Kivu, on the shore of Lake Kivu at the foot of the active Mount Nyiragongo volcano.",
    fullBiography:
      "Goma sits on the northern shore of Lake Kivu near the DRC's border with Rwanda, about 12 km south of Mount Nyiragongo, one of the world's most active volcanoes. A 2002 eruption killed more than 250 people and left 120,000 homeless; a 2021 eruption destroyed thousands of homes. Goma has long served as a hub for humanitarian operations in eastern Congo amid recurring conflict in North Kivu, including the M23 rebel offensive that took control of the city in January 2025.",
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/5/50/Goma%2C_Nord_Kivu%2C_RD_Congo_-_Vue_a%C3%A9rienne_partielle_de_la_ville_de_Goma._%2823720614532%29.jpg",
    sourceUrl:
      "https://commons.wikimedia.org/wiki/File:Goma,_Nord_Kivu,_RD_Congo_-_Vue_a%C3%A9rienne_partielle_de_la_ville_de_Goma._(23720614532).jpg",
    sourceName: "Photo: MONUSCO/Michael Ali, via Wikimedia Commons (CC BY-SA 2.0)",
    keywords: ["goma", "north kivu", "lake kivu", "nyiragongo", "city"],
    aliases: [],
    active: true,
    featured: true,
    verified: true,
  },
  {
    slug: "kisangani",
    name: "Kisangani",
    category: "Cities",
    province: "Tshopo",
    country: "DR Congo",
    shortDescription:
      "The DRC's fifth-largest city, a historic river port at the northernmost navigable point of the Congo River.",
    fullBiography:
      "Founded by Europeans in 1883 and known successively as Falls Station and Stanleyville, Kisangani is the capital of Tshopo Province and sits at the junction of the Congo, Tshopo, and Lindi rivers, about 80 km from the equator. It marks the northern limit of navigation for large cargo vessels on the Congo River between Kinshasa and Kisangani, making it a key trading link between eastern and western Congo.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/c/cb/Aerial_view_of_the_Congo_River_near_Kisangani.jpg",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Aerial_view_of_the_Congo_River_near_Kisangani.jpg",
    sourceName: "Photo: MONUSCO/Myriam Asmani, via Wikimedia Commons (CC BY-SA 2.0)",
    keywords: ["kisangani", "tshopo", "congo river", "city"],
    aliases: ["Stanleyville", "Falls Station"],
    active: true,
    featured: false,
    verified: true,
  },
  {
    slug: "bukavu",
    name: "Bukavu",
    category: "Cities",
    province: "South Kivu",
    country: "DR Congo",
    shortDescription:
      "The capital of South Kivu, on the southwestern shore of Lake Kivu, known for its Belgian-era art deco architecture.",
    fullBiography:
      "Bukavu sits on a peninsula at the southwestern edge of Lake Kivu, across the Ruzizi River from Rwanda, and serves as South Kivu's provincial capital and a regional commercial and lake-port center. The city retains more than 100 art deco buildings from the Belgian colonial period. Like much of eastern Congo, Bukavu has been affected by recurring conflict, including its capture by M23 rebels in February 2025.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/0/03/Laville_de_bukavu_vue_du_lac.jpg",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Laville_de_bukavu_vue_du_lac.jpg",
    sourceName: "Photo: Cedrickarungu921, via Wikimedia Commons (CC0)",
    keywords: ["bukavu", "south kivu", "lake kivu", "city"],
    aliases: [],
    active: true,
    featured: false,
    verified: true,
  },
  {
    slug: "mbuji-mayi",
    name: "Mbuji-Mayi",
    category: "Cities",
    province: "Kasaï-Oriental",
    country: "DR Congo",
    shortDescription:
      "The capital of Kasaï-Oriental and the traditional center of the DRC's industrial diamond mining industry.",
    fullBiography:
      "Mbuji-Mayi, formerly known as Bakwanga, is among the DRC's most populous cities and sits atop one of the largest known diamond deposits in the world. The state mining company MIBA, headquartered in the city, was once the source of a majority of the world's industrial diamonds. Despite this mineral wealth, the city has faced significant economic hardship in recent decades.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/5/5d/A%C3%A9roport_de_Mbuji-Mayi.jpg",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:A%C3%A9roport_de_Mbuji-Mayi.jpg",
    sourceName: "Photo: MONUSCO/Myriam Asmani, via Wikimedia Commons (CC BY-SA 2.0)",
    keywords: ["mbuji-mayi", "kasai-oriental", "diamonds", "mining", "city"],
    aliases: ["Bakwanga"],
    active: true,
    featured: false,
    verified: true,
  },
  {
    slug: "matadi",
    name: "Matadi",
    category: "Cities",
    province: "Kongo Central",
    country: "DR Congo",
    shortDescription:
      "The DRC's chief seaport and the capital of Kongo Central province, on the Congo River near the Atlantic coast.",
    fullBiography:
      "Founded by Henry Morton Stanley in 1879, Matadi is the last navigable port on the Congo River before the rapids that block further passage upstream, making it the DRC's principal maritime gateway. The Matadi–Kinshasa railway, built between 1890 and 1898, connected the port to the interior. The Matadi Bridge, completed in 1983, is the only bridge across the main stem of the Congo River.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/9/96/Matadi_Bridge_DR_Congo.jpg",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Matadi_Bridge_DR_Congo.jpg",
    sourceName: "Photo: Christos Immanuel, via Wikimedia Commons (CC BY-SA 4.0)",
    keywords: ["matadi", "kongo central", "port", "matadi bridge", "city"],
    aliases: [],
    active: true,
    featured: false,
    verified: true,
  },
  {
    slug: "kananga",
    name: "Kananga",
    category: "Cities",
    province: "Kasaï-Central",
    country: "DR Congo",
    shortDescription:
      "The capital of Kasaï-Central and one of the DRC's most populous cities, formerly known as Luluabourg.",
    fullBiography:
      "Founded around a station established by explorer Hermann Wissmann in the 1880s and later renamed Luluabourg after a nearby railway stop, the city was renamed Kananga in 1966 during Mobutu Sese Seko's campaign to replace colonial-era place names. It served briefly as the seat of the secessionist South Kasai state in the early 1960s and hosted the drafting of the DRC's first Congolese-written constitution in 1964. Kananga is today the capital of Kasaï-Central Province and one of the country's most populous urban centers.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/f/f6/Aerial_photograph_of_Kananga.jpg",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Aerial_photograph_of_Kananga.jpg",
    sourceName: "Photo: MONUSCO/Myriam Asmani, via Wikimedia Commons (CC BY-SA 2.0)",
    keywords: ["kananga", "kasai-central", "luluabourg", "city"],
    aliases: ["Luluabourg"],
    active: true,
    featured: false,
    verified: true,
  },
  {
    slug: "kolwezi",
    name: "Kolwezi",
    category: "Cities",
    province: "Lualaba",
    country: "DR Congo",
    shortDescription:
      "The capital of Lualaba Province, known as the DRC's mining center for copper and cobalt, home to some of the world's largest cobalt reserves.",
    fullBiography:
      "Industrial development at Kolwezi began around 1901, and the Belgian mining company Union Minière du Haut Katanga (predecessor of the state-owned Gécamines) established operations there in 1906, building the city into a major copper-mining center. Today Kolwezi sits atop a large share of the world's known cobalt reserves and remains central to global battery-metal supply chains, alongside continued copper production. The city was also the site of a violent 1978 conflict remembered as the Battle of Kolwezi.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/c/c7/Kamoto_Mine_-_panoramio.jpg",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Kamoto_Mine_-_panoramio.jpg",
    sourceName: "Photo: Martin Tuchscherer, via Wikimedia Commons (CC BY-SA 3.0)",
    keywords: ["kolwezi", "lualaba", "cobalt", "copper", "mining", "city"],
    aliases: [],
    active: true,
    featured: true,
    verified: true,
  },
  {
    slug: "boma",
    name: "Boma",
    category: "Cities",
    province: "Kongo Central",
    country: "DR Congo",
    shortDescription:
      "A historic port city on the Congo River near the Atlantic coast, and the former capital of the Congo Free State and Belgian Congo.",
    fullBiography:
      "Boma served as the capital of the Congo Free State and later the Belgian Congo from 1886 until 1923, when the colonial administration relocated the capital to Léopoldville (Kinshasa). Located roughly 100 km upstream from the Atlantic Ocean on the Congo River, Boma remains an active port handling exports including timber, bananas, cocoa, and palm products, and sits near the river's mouth, close to the country's border with Angola.",
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/f/f0/Boma%2C_Congo%2C_ca._1900-1915_%28IMP-CSCNWW33-OS11-74%29.jpg",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Boma,_Congo,_ca._1900-1915_(IMP-CSCNWW33-OS11-74).jpg",
    sourceName:
      "Photo: International Mission Photography Archive, Congo Balolo Mission collection, via Wikimedia Commons (public domain, pre-1931)",
    keywords: ["boma", "kongo central", "port", "former capital", "congo free state", "city"],
    aliases: [],
    active: true,
    featured: false,
    verified: true,
  },
  {
    slug: "bunia",
    name: "Bunia",
    category: "Cities",
    province: "Ituri",
    country: "DR Congo",
    shortDescription:
      "The capital of Ituri Province, established in 1946 to support the nearby Kilo-Moto gold mines.",
    fullBiography:
      "Bunia was founded in 1946 as an administrative center serving the Kilo-Moto gold mines, among the largest gold-mining operations in Africa, and sits on a plateau near Lake Albert in the Albertine Rift. It became the capital of Ituri Province following that province's creation in 2005. Bunia and the surrounding Ituri region saw intense fighting during the Ituri conflict between Hema and Lendu communities, particularly during the Second Congo War, and the city remains an important administrative and economic center for the province.",
    publishedDate: "1946-01-01",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/c/c4/Bunia.JPG",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Bunia.JPG",
    sourceName: "Photo: HokieRNB (Russell N. Brown), via Wikimedia Commons (public domain)",
    keywords: ["bunia", "ituri", "kilo-moto", "city"],
    aliases: [],
    active: true,
    featured: false,
    verified: true,
  },
  {
    slug: "uvira",
    name: "Uvira",
    category: "Cities",
    province: "South Kivu",
    country: "DR Congo",
    shortDescription:
      "A port city at the northern tip of Lake Tanganyika, in South Kivu, and a key trade hub bordering Burundi.",
    fullBiography:
      "Uvira sits at the northernmost point of Lake Tanganyika in South Kivu Province, near the DRC's border with Burundi. It developed from the early 1900s as a garrison of the Congo Free State, serving as an entry point via Lake Tanganyika and a base for monitoring nearby German East Africa. Its lake port, Kalundu, connects Uvira by boat to Kalemie, Kigoma (Tanzania), Bujumbura (Burundi), and Mpulungu (Zambia), making the city a regional trade hub. Uvira gained official city status by presidential decree in 2018, the second in South Kivu after Bukavu.",
    publishedDate: "2018-01-01",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/f/fb/VILLE_D%27UVIRA.jpg",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:VILLE_D%27UVIRA.jpg",
    sourceName: "Photo: Mukengere karume, via Wikimedia Commons (CC0)",
    keywords: ["uvira", "south kivu", "lake tanganyika", "city"],
    aliases: [],
    active: true,
    featured: false,
    verified: true,
  },

  // ---- Nature: rivers, forests, protected areas, and species. Every
  // statistic below is attributed to a specific dated source rather than
  // stated as a flat fact — population/size/elevation figures shift
  // between surveys, so the in-text date matters as much as the number.
  // Images used only where a specific Commons file's license was
  // individually verified; left blank otherwise (see Lomami National Park).
  {
    slug: "congo-river",
    name: "Congo River",
    category: "Nature",
    subcategory: "River",
    province: "Multiple provinces",
    country: "DR Congo",
    shortDescription:
      "Africa's second-longest river and the world's deepest, flowing through the Congo Basin and crossing the equator twice.",
    fullBiography:
      "The Congo River (with its Lualaba headwaters) runs about 4,700 km (2,900 mi), making it Africa's second-longest river after the Nile. Its drainage basin covers roughly 4,014,500 km² — about 13% of Africa's landmass — spanning ten countries, with the DRC accounting for the majority of that basin. It is the world's deepest recorded river, with measured depths of around 220 m (720 ft), and carries the second-largest average discharge of any river on Earth after the Amazon. Unusually, it crosses the equator twice along its course.",
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/9/93/Congo_River_with_upstream_half_of_Pool_Malebo_and_Mbamu.jpg",
    sourceUrl: "https://en.wikipedia.org/wiki/Congo_River",
    sourceName: "Photo: Dicklyon, via Wikimedia Commons (CC BY-SA 4.0); Wikipedia: Congo River",
    keywords: ["congo river", "river", "nature", "waterway"],
    aliases: ["Fleuve Congo", "Zaire River"],
    active: true,
    featured: true,
    verified: true,
  },
  {
    slug: "congo-basin-rainforest",
    name: "Congo Basin Rainforest",
    category: "Nature",
    subcategory: "Rainforest",
    province: "Multiple provinces",
    country: "DR Congo",
    shortDescription:
      "The world's second-largest rainforest after the Amazon, spanning ten Central African countries and storing a significant share of the world's forest-based carbon.",
    fullBiography:
      "The Congo Basin holds roughly 300 million hectares of rainforest, making it the second-largest contiguous tropical rainforest on Earth after the Amazon's 800 million hectares, within a broader 3.7 million km² basin spanning ten countries. The DRC contains the largest share of this forest. The region is estimated to store roughly 8% of the world's forest-based carbon, and peatlands discovered in its central Cuvette Centrale in 2017 were estimated to hold around 30 billion tonnes of carbon. The basin is home to thousands of plant species and iconic wildlife including western lowland gorillas, forest elephants, okapi, bonobos, and chimpanzees, though as of that research only about 14% of the basin's humid forest carried formal protected status.",
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/f/f9/Popcorn_Clouds_in_the_Congo_Basin_%28MODIS%29.jpg",
    sourceUrl: "https://en.wikipedia.org/wiki/Congo_Basin",
    sourceName: "Satellite image: NASA MODIS Land Rapid Response Team (public domain); Wikipedia: Congo Basin",
    keywords: ["congo basin", "rainforest", "forest", "nature", "carbon"],
    aliases: ["Congo rainforest"],
    active: true,
    featured: true,
    verified: true,
  },
  {
    slug: "virunga-national-park",
    name: "Virunga National Park",
    category: "Nature",
    subcategory: "National Park",
    province: "North Kivu",
    country: "DR Congo",
    shortDescription:
      "Africa's oldest national park, established in 1925, home to mountain gorillas and two active volcanoes.",
    fullBiography:
      "Established in April 1925 as Albert National Park and renamed Virunga in 1969, this is Africa's oldest national park, covering about 7,800 km² in the Albertine Rift along the DRC's borders with Uganda and Rwanda. UNESCO designated it a World Heritage Site in 1979, and it has been listed as a World Heritage Site in Danger since 1994 due to armed conflict and poaching. Elevation ranges from 680 m in the Semliki River valley to over 5,100 m in the Rwenzori Mountains, and the park contains two active volcanoes, Mount Nyiragongo and Nyamuragira. It protects part of the mountain gorilla's range alongside more than 3,000 recorded plant and animal species.",
    publishedDate: "1925-04-01",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/6/68/Virunga_National_Park_%2831437399312%29.jpg",
    sourceUrl: "https://en.wikipedia.org/wiki/Virunga_National_Park",
    sourceName: "Photo: Nina R, via Wikimedia Commons (CC BY 2.0); Wikipedia: Virunga National Park",
    keywords: ["virunga", "national park", "north kivu", "mountain gorilla", "unesco", "nature"],
    aliases: ["Albert National Park"],
    active: true,
    featured: true,
    verified: true,
  },
  {
    slug: "kahuzi-biega-national-park",
    name: "Kahuzi-Biega National Park",
    category: "Nature",
    subcategory: "National Park",
    province: "South Kivu",
    country: "DR Congo",
    shortDescription:
      "A UNESCO World Heritage Site west of Bukavu, established in 1970 to protect the eastern lowland (Grauer's) gorilla.",
    fullBiography:
      "Established in November 1970 by conservationist Adrien Deschryver (building on an earlier 1937 reserve), Kahuzi-Biega National Park covers about 6,000 km², combining a smaller mountainous eastern sector with a much larger lowland western sector connected by a narrow forest corridor. It lies west of Bukavu in South Kivu Province, near Lake Kivu and the Rwandan border. UNESCO listed it as a World Heritage Site in 1980 and added it to the endangered list in 1997 amid regional instability and wildlife exploitation. The park protects the eastern lowland gorilla (also called Grauer's gorilla) — a 2011 survey recorded 181 individuals, up from 125 in 2008 — alongside forest elephants, chimpanzees, and one of the highest counts of mammal species in the Albertine Rift.",
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/b/b6/Kahuzi-Biega_National_Park_%2839423247252%29.jpg",
    sourceUrl: "https://en.wikipedia.org/wiki/Kahuzi-Bi%C3%A9ga_National_Park",
    sourceName: "Photo: USDA Forest Service / Roni Ziade, via Wikimedia Commons (public domain)",
    keywords: ["kahuzi-biega", "national park", "south kivu", "grauer's gorilla", "eastern lowland gorilla", "unesco"],
    aliases: ["Kahuzi-Biéga"],
    active: true,
    featured: false,
    verified: true,
  },
  {
    slug: "salonga-national-park",
    name: "Salonga National Park",
    category: "Nature",
    subcategory: "National Park",
    province: "Mai-Ndombe / Équateur / Kasaï / Sankuru",
    country: "DR Congo",
    shortDescription:
      "Africa's largest tropical rainforest reserve, accessible only by river, and a key stronghold for bonobos and Congo peafowl.",
    fullBiography:
      "First protected as Tshuapa National Park in 1956 and given its current boundaries by a 1970 presidential decree, Salonga National Park covers about 36,000 km² (3.6 million hectares) across the Mai-Ndombe, Équateur, Kasaï, and Sankuru provinces, making it Africa's largest tropical rainforest reserve. UNESCO listed it as a World Heritage Site in 1984, added it to the endangered list in 1999 due to poaching and infrastructure pressure, and removed that designation in 2021. The park has no roads and is reached primarily by river. It is a significant stronghold for bonobos and hosts forest elephants, leopards, bongo antelope, and the Congo peafowl, the DRC's national bird.",
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/5/54/La_rivi%C3%A8re_Lulilaka%2C_parc_national_de_Salonga%2C_2005.jpg",
    sourceUrl: "https://en.wikipedia.org/wiki/Salonga_National_Park",
    sourceName: "Photo: Radio Okapi, via Wikimedia Commons (CC BY 2.0); Wikipedia: Salonga National Park",
    keywords: ["salonga", "national park", "bonobo", "congo peafowl", "unesco", "rainforest"],
    aliases: ["Tshuapa National Park"],
    active: true,
    featured: true,
    verified: true,
  },
  {
    slug: "garamba-national-park",
    name: "Garamba National Park",
    category: "Nature",
    subcategory: "National Park",
    province: "Haut-Uélé",
    country: "DR Congo",
    shortDescription:
      "One of Africa's oldest national parks, established in 1938 in the northeastern DRC, historically home to the now-extinct-in-the-wild northern white rhino.",
    fullBiography:
      "Established in 1938 in the northeastern DRC near the South Sudan border, Garamba National Park covers about 5,200 km², making it one of Africa's oldest protected areas. UNESCO designated it a World Heritage Site in 1980; it has been on the endangered list for most of the period since 1984 due to sustained poaching pressure. Garamba once held the last wild population of the northern white rhinoceros, which has since gone extinct in the wild — surveys found only 15 individuals in the mid-1980s. Elephant numbers in the park fell from roughly 20,000 in the 1960s–70s to fewer than 2,000 by 2017, though poaching incidents fell sharply from 98 recorded in 2015 to 3 in 2022. The park hosts the DRC's only remaining wild giraffe population, the Kordofan subspecies.",
    publishedDate: "1938-01-01",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/7/7e/Kordofan_giraffe_in_Garamba_National_Park.jpg",
    sourceUrl: "https://en.wikipedia.org/wiki/Garamba_National_Park",
    sourceName: "Photo: Matthew Luizza / U.S. Fish and Wildlife Service, via Wikimedia Commons (public domain)",
    keywords: ["garamba", "national park", "haut-uele", "white rhino", "giraffe", "elephant", "unesco"],
    aliases: [],
    active: true,
    featured: false,
    verified: true,
  },
  {
    slug: "okapi-wildlife-reserve",
    name: "Okapi Wildlife Reserve",
    category: "Nature",
    subcategory: "Wildlife Reserve",
    province: "Ituri",
    country: "DR Congo",
    shortDescription:
      "A UNESCO World Heritage Site covering about a fifth of the Ituri Forest, established in 1992 to protect the okapi and its rainforest habitat.",
    fullBiography:
      "Established in 1992 and inscribed as a UNESCO World Heritage Site in 1996 (added to the endangered list the following year), the Okapi Wildlife Reserve covers roughly 13,726 km² — about one-fifth of the Ituri Forest — in northeastern DRC near the South Sudan and Uganda borders. The reserve protects a Pleistocene forest refugium that stayed forested through past ice ages, supporting 17 primate species (the most of any African forest) and over 370 bird species, including the Congo peafowl. A 1996 estimate put its okapi population at roughly 3,900–6,350 individuals, representing a substantial share of the global population, alongside similarly dated estimates of about 7,500 elephants and 7,500 chimpanzees. The reserve faces ongoing threats from armed conflict, illegal gold mining, and poaching.",
    publishedDate: "1992-01-01",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/8/8f/Epulu_Okapi_Reserve.jpg",
    sourceUrl: "https://en.wikipedia.org/wiki/Okapi_Wildlife_Reserve",
    sourceName: "Photo: J. Doremus / USAID, via Wikimedia Commons (public domain)",
    keywords: ["okapi wildlife reserve", "ituri", "okapi", "unesco", "wildlife reserve"],
    aliases: ["Okapi Faunal Reserve"],
    active: true,
    featured: true,
    verified: true,
  },
  {
    slug: "lomami-national-park",
    name: "Lomami National Park",
    category: "Nature",
    subcategory: "National Park",
    province: "Tshopo / Maniema",
    country: "DR Congo",
    shortDescription:
      "The DRC's ninth national park, created in 2016 in the Lomami River basin — the first new national park in the country since 1992.",
    fullBiography:
      "Created on July 7, 2016, Lomami National Park covers about 8,879 km² across Tshopo and Maniema provinces, between Kisangani and Kindu. It was the DRC's ninth national park and the first established in the country since 1992, following community consultations held from 2010 to 2012 that included traditional ceremonies with local villages to help define its boundaries. The park protects bonobos, okapi, forest elephants, and the Congo peafowl, and is notable as the home range of the lesula monkey, a species first identified in 2007 and endemic to the region. Its principal conservation challenges are the bushmeat trade and elephant poaching for ivory.",
    publishedDate: "2016-07-07",
    sourceUrl: "https://en.wikipedia.org/wiki/Lomami_National_Park",
    sourceName: "Wikipedia: Lomami National Park",
    keywords: ["lomami", "national park", "tshopo", "maniema", "bonobo", "lesula monkey"],
    aliases: [],
    active: true,
    featured: false,
    verified: true,
  },
  {
    slug: "lake-kivu",
    name: "Lake Kivu",
    category: "Nature",
    subcategory: "Lake",
    province: "North Kivu / South Kivu",
    country: "DR Congo",
    shortDescription:
      "One of Africa's Great Lakes, shared with Rwanda, notable for the vast reserves of dissolved methane and carbon dioxide trapped in its depths.",
    fullBiography:
      "Lake Kivu covers about 2,700 km², making it Africa's eighth-largest lake, and sits on the DRC–Rwanda border, with roughly 58% of its waters on the Congolese side. Its surface sits at 1,460 m elevation, with a maximum depth of about 480 m. The lake is meromictic, meaning its deep water layers do not mix with the surface — as a result it holds an estimated 65 km³ of dissolved methane and 256 km³ of carbon dioxide, raising a long-studied risk of a limnic eruption that could endanger the roughly two million people living around its shores. Methane extraction projects, including the KivuWatt plant, have tapped this gas for power generation. The lake drains south into the Ruzizi River toward Lake Tanganyika.",
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/2/20/Goma%2C_Lake_Kivu%2C_DRC_%28Zaire_-_Congo%29%2C_Photo_by_Sascha_Grabow.jpg",
    sourceUrl: "https://en.wikipedia.org/wiki/Lake_Kivu",
    sourceName: "Photo: Sascha Grabow, via Wikimedia Commons (CC BY-SA 3.0); Wikipedia: Lake Kivu",
    keywords: ["lake kivu", "lake", "north kivu", "south kivu", "methane", "nature"],
    aliases: [],
    active: true,
    featured: true,
    verified: true,
  },
  {
    slug: "lake-tanganyika",
    name: "Lake Tanganyika",
    category: "Nature",
    subcategory: "Lake",
    province: "Tanganyika / South Kivu",
    country: "DR Congo",
    shortDescription:
      "The world's longest freshwater lake and second-deepest, shared by the DRC, Tanzania, Burundi, and Zambia, with exceptional cichlid biodiversity.",
    fullBiography:
      "Lake Tanganyika covers about 32,900 km² and stretches roughly 673 km in length, making it the world's longest freshwater lake. With a maximum depth of about 1,470 m, it is the world's second-deepest lake after Lake Baikal and holds an estimated 16% of the planet's available surface fresh water. It is shared among four countries, with Tanzania (about 46%) and the DRC (about 40%) holding the largest shares of its area. As one of only about twenty lakes on Earth older than a million years, it has developed exceptional biodiversity, including at least 250 endemic cichlid fish species.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/6/61/Lake_Tanganyika.jpg",
    sourceUrl: "https://en.wikipedia.org/wiki/Lake_Tanganyika",
    sourceName: "Photo: Orrling, via Wikimedia Commons (CC BY-SA 3.0); Wikipedia: Lake Tanganyika",
    keywords: ["lake tanganyika", "lake", "tanganyika", "south kivu", "cichlid", "nature"],
    aliases: [],
    active: true,
    featured: false,
    verified: true,
  },
  {
    slug: "mount-nyiragongo",
    name: "Mount Nyiragongo",
    category: "Nature",
    subcategory: "Volcano",
    province: "North Kivu",
    country: "DR Congo",
    shortDescription:
      "An active stratovolcano near Goma with one of the world's largest persistent lava lakes, among the most active and dangerous volcanoes on Earth.",
    fullBiography:
      "Mount Nyiragongo rises to 3,470 m in the Virunga Mountains, about 12 km north of Goma, within Virunga National Park. Its roughly two-kilometer-wide crater typically holds a large, persistent lava lake. The volcano has erupted with major loss of life multiple times: in January 1977, a fracture in the crater wall drained the lava lake within an hour, with fast-moving lava killing at least 50 people; a 2002 eruption killed about 245 people and covered part of Goma in lava; and a 2021 eruption killed at least 32 people and destroyed 17 villages. Eruptive activity has continued intermittently since, including a new episode reported from February 2024. Along with the neighboring Nyamuragira volcano, Nyiragongo accounts for a large share of Africa's historical volcanic eruptions, and was designated a \"Decade Volcano\" in 1991 for its hazard potential.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/7/76/Lava_Lake_Nyiragongo_2.jpg",
    sourceUrl: "https://en.wikipedia.org/wiki/Mount_Nyiragongo",
    sourceName: "Photo: Cai Tjeenk Willink, via Wikimedia Commons (CC BY-SA 3.0); Wikipedia: Mount Nyiragongo",
    keywords: ["nyiragongo", "volcano", "north kivu", "goma", "lava lake", "virunga"],
    aliases: [],
    active: true,
    featured: true,
    verified: true,
  },
  {
    slug: "rwenzori-mountains",
    name: "Rwenzori Mountains",
    category: "Nature",
    subcategory: "Mountain Range",
    province: "North Kivu",
    country: "DR Congo",
    shortDescription:
      "A glaciated, non-volcanic mountain range on the DRC–Uganda border, home to the DRC's highest point and long associated with Ptolemy's legendary \"Mountains of the Moon.\"",
    fullBiography:
      "The Rwenzori Mountains stretch about 120 km long and 65 km wide along the border between the DRC and Uganda. Their highest point, Margherita Peak on Mount Stanley, reaches 5,109 m, making it the DRC's highest point and among the highest peaks in Africa. Formed roughly three million years ago through geological uplift rather than volcanic activity, the range is described as the highest non-volcanic, non-orogenic mountains in the world, and comprises six main massifs separated by deep gorges. Rivers draining the range feed into the Nile system, a connection that led early European explorers to associate the Rwenzoris with the ancient geographer Ptolemy's legendary \"Mountains of the Moon.\" Most of the range carries UNESCO World Heritage status, jointly covered by Rwenzori Mountains National Park in Uganda and Virunga National Park in the DRC.",
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/4/4f/Ruwenzori_Mountains_Virunga_National_Park.jpg",
    sourceUrl: "https://en.wikipedia.org/wiki/Rwenzori_Mountains",
    sourceName: "Photo: Cai Tjeenk Willink, via Wikimedia Commons (CC BY-SA 3.0); Wikipedia: Rwenzori Mountains",
    keywords: ["rwenzori", "mountains", "north kivu", "margherita peak", "mount stanley", "unesco"],
    aliases: ["Ruwenzori", "Mountains of the Moon"],
    active: true,
    featured: false,
    verified: true,
  },
  {
    slug: "boyoma-falls",
    name: "Boyoma Falls",
    category: "Nature",
    subcategory: "Waterfall",
    province: "Tshopo",
    country: "DR Congo",
    shortDescription:
      "A series of seven cataracts on the Lualaba River near Kisangani, and, by average flow rate, the largest waterfall in the world.",
    fullBiography:
      "Boyoma Falls, formerly called Stanley Falls, is a series of seven cataracts spread over more than 100 km of the Lualaba River between Ubundu and Kisangani in Tshopo Province. No single cataract exceeds about 5 m in height, but the combined drop across the series totals about 61 m. With an average flow rate of roughly 16,990 m³/s, it is considered, by volume, the largest waterfall in the world, surpassing Niagara and Iguazu Falls. The final cataract, known as Wagenia Falls, is named for the Indigenous Wagenia (Wagenya) fishermen, who use large wooden tripod-and-basket traps anchored in the rapids to catch fish — a technique documented since the 19th century.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/1/19/Aembe_au_Chutes_Wagenia_Kisangani.jpg",
    sourceUrl: "https://en.wikipedia.org/wiki/Boyoma_Falls",
    sourceName: "Photo: Ginembolisamarie, via Wikimedia Commons (CC BY-SA 4.0); Wikipedia: Boyoma Falls",
    keywords: ["boyoma falls", "stanley falls", "wagenia falls", "kisangani", "tshopo", "waterfall"],
    aliases: ["Stanley Falls", "Wagenia Falls"],
    active: true,
    featured: false,
    verified: true,
  },
  {
    slug: "livingstone-falls",
    name: "Livingstone Falls",
    category: "Nature",
    subcategory: "Waterfall",
    province: "Kongo Central",
    country: "DR Congo",
    shortDescription:
      "A 350-km series of rapids on the lower Congo River between Kinshasa and Matadi that blocks navigation and, by discharge, ranks among the world's largest waterfalls.",
    fullBiography:
      "Livingstone Falls is a roughly 350-km succession of rapids and cataracts on the Congo River downstream of Malebo Pool, ending near Matadi in Kongo Central Province, with a total drop of about 270 m. The river channel narrows dramatically through this stretch, in places to under 300 m wide, while reaching depths of up to 200 m between rapids. Carrying the world's second-largest river discharge after the Amazon, Livingstone Falls is often cited as the world's largest waterfall by flow rate, though technically it is a long series of rapids rather than a single fall. The rapids form an impassable barrier to river navigation, which is why the Matadi–Kinshasa railway was built to bypass them; the powerful, turbulent channel has also isolated fish populations enough to drive localized speciation.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/4/4e/Livingstone_Falls.jpg",
    sourceUrl: "https://en.wikipedia.org/wiki/Livingstone_Falls",
    sourceName: "Photo: Henry M. Stanley, via Wikimedia Commons (public domain, pre-1931); Wikipedia: Livingstone Falls",
    keywords: ["livingstone falls", "congo river", "kongo central", "matadi", "waterfall", "rapids"],
    aliases: [],
    active: true,
    featured: false,
    verified: true,
  },
  {
    slug: "lola-ya-bonobo",
    name: "Lola ya Bonobo",
    category: "Nature",
    subcategory: "Wildlife Sanctuary",
    province: "Kinshasa",
    country: "DR Congo",
    shortDescription:
      "The world's only sanctuary dedicated to orphaned bonobos, founded in 1994 by Claudine André near Kinshasa.",
    fullBiography:
      "Founded in 1994 by conservationist Claudine André and relocated to its current site near Kimwenza, south of Kinshasa, in 2002, Lola ya Bonobo is described as the world's only sanctuary for orphaned bonobos rescued from the bushmeat and pet trades. The sanctuary rehabilitates confiscated bonobos on a forested site and runs conservation education programs for Congolese visitors. It is a member of the Pan African Sanctuary Alliance and partners with the associated Ekolo ya Bonobo Community Reserve in Équateur Province, where rehabilitated bonobos have been reintroduced to the wild in staged releases beginning in 2008.",
    publishedDate: "1994-01-01",
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/3/32/Bonobo_%28Pan_paniscus%29_at_Lola_Ya_Bonobo_-_3.JPG",
    sourceUrl: "https://en.wikipedia.org/wiki/Lola_ya_Bonobo",
    sourceName: "Photo: Christina Bergey, via Wikimedia Commons (CC BY-SA 3.0); Wikipedia: Lola ya Bonobo",
    keywords: ["lola ya bonobo", "bonobo sanctuary", "kinshasa", "claudine andre", "wildlife sanctuary"],
    aliases: [],
    active: true,
    featured: true,
    verified: true,
  },
  {
    slug: "mountain-gorilla",
    name: "Mountain Gorilla",
    category: "Nature",
    subcategory: "Wildlife Species",
    province: "North Kivu / South Kivu",
    country: "DR Congo",
    shortDescription:
      "An IUCN-listed Endangered great ape found only in the Virunga Mountains and Uganda's Bwindi forest, distinguished by thick fur adapted to cold, high-altitude habitat.",
    fullBiography:
      "The mountain gorilla (Gorilla beringei beringei) is classified as Endangered by the IUCN (2018 assessment) and listed on CITES Appendix I. It survives in two isolated populations: the Virunga Massif, spanning Virunga National Park in the DRC and adjoining parks in Rwanda and Uganda, and Uganda's Bwindi Impenetrable Forest, at elevations between roughly 2,200 and 4,300 m. A rangewide census reported approximately 1,063 individuals as of 2019, up from about 480 recorded in the Virunga region alone in a 2010 census. Compared to other gorilla subspecies, mountain gorillas have notably thicker, longer fur, an adaptation to their cool, high-altitude habitat. Adult males develop a distinctive silver saddle of hair on their backs with age, and each individual can be identified by a unique nose print.",
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/6/6b/Mountain_gorilla_%28Gorilla_beringei_beringei%29_eating.jpg",
    sourceUrl: "https://en.wikipedia.org/wiki/Mountain_gorilla",
    sourceName: "Photo: Charles J. Sharp, via Wikimedia Commons (CC BY-SA 4.0); Wikipedia: Mountain gorilla",
    keywords: ["mountain gorilla", "gorilla", "virunga", "wildlife", "endangered species"],
    aliases: [],
    active: true,
    featured: true,
    verified: true,
  },
  {
    slug: "bonobo",
    name: "Bonobo",
    category: "Nature",
    subcategory: "Wildlife Species",
    province: "Congo Basin (south of the Congo River)",
    country: "DR Congo",
    shortDescription:
      "An Endangered great ape found only in the DRC, south of the Congo River, known for its matriarchal, female-led social structure.",
    fullBiography:
      "The bonobo (Pan paniscus) is classified as Endangered by the IUCN and listed on CITES Appendix I. It is found exclusively in the Democratic Republic of the Congo, in a range covering an estimated 500,000 km² of the Congo Basin south of the Congo River and north of the Kasai River. Bonobo population estimates vary considerably between assessments — figures cited range roughly from 30,000 to 50,000 individuals — reflecting how difficult the species is to survey across dense, often inaccessible forest, though most assessments agree the population has declined significantly in recent decades. The smallest of the great apes, bonobos are distinguished from common chimpanzees by longer limbs, pinker lips, a darker face, and a persistent tail-tuft into adulthood. They are best known for a matriarchal social structure in which female alliances dominate group life.",
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/6/6f/Bonobo_at_Nsele_Valley_Park%2C_Kinshasa%2C_DR_Congo.jpg",
    sourceUrl: "https://en.wikipedia.org/wiki/Bonobo",
    sourceName: "Photo: EdwinAlden.1995, via Wikimedia Commons (CC BY-SA 4.0); Wikipedia: Bonobo",
    keywords: ["bonobo", "great ape", "congo basin", "wildlife", "endangered species"],
    aliases: ["pygmy chimpanzee"],
    active: true,
    featured: true,
    verified: true,
  },
  {
    slug: "okapi",
    name: "Okapi",
    category: "Nature",
    subcategory: "Wildlife Species",
    province: "Ituri / Tshopo",
    country: "DR Congo",
    shortDescription:
      "An Endangered forest relative of the giraffe, striped like a zebra and native only to the northeastern DRC's rainforests.",
    fullBiography:
      "The okapi (Okapia johnstoni) is classified as Endangered by the IUCN. It is endemic to the rainforests of northeastern DRC, north and east of the Congo River, living at elevations of roughly 500 to 1,500 m. Reliable range-wide population counts are not well established, though researchers have long documented a steady decline linked to habitat loss, poaching, and armed conflict in its range. Okapis stand about 1.5 m at the shoulder and are covered in a chocolate-to-reddish-brown coat with distinctive white horizontal stripes on the legs, a pattern that provides camouflage in dense forest despite its resemblance to a zebra's markings. Genetic evidence indicates the okapi's closest living relative is the giraffe, with the two species' common ancestor dating to roughly 11.5 million years ago — together they make up the only two living members of the giraffe family. The photograph used here shows a captive individual; okapis are notoriously difficult to photograph in the wild.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/a/a7/The_Rare_Okapi_%2810549264174%29.jpg",
    sourceUrl: "https://en.wikipedia.org/wiki/Okapi",
    sourceName: "Photo: Steve Wilson, via Wikimedia Commons (CC BY 2.0); Wikipedia: Okapi",
    keywords: ["okapi", "ituri", "giraffe relative", "wildlife", "endangered species"],
    aliases: ["forest giraffe"],
    active: true,
    featured: true,
    verified: true,
  },
  {
    slug: "congo-peafowl",
    name: "Congo Peafowl",
    category: "Nature",
    subcategory: "Wildlife Species",
    province: "Central Congolian lowland forests",
    country: "DR Congo",
    shortDescription:
      "The DRC's national bird, a Near Threatened peafowl species endemic to the country's lowland rainforests and only formally described in 1936.",
    fullBiography:
      "The Congo peafowl (Afropavo congensis), also known as the Congo peacock, is classified as Near Threatened by the IUCN (2022 assessment). It is endemic to the Central Congolian lowland forests of the DRC, including Salonga and Maiko National Parks, and is designated the country's national bird. As of a 2013 IUCN Red List assessment, the wild population was estimated at between 2,500 and 9,000 adult individuals. The species was identified in 1934 by ornithologist James P. Chapin, who recognized unfamiliar feathers in local headdresses as belonging to an undescribed species rather than the Indian peafowl; it was formally described in 1936 after he located living specimens. Males display deep blue plumage with metallic green and violet iridescence, bare red neck skin, and a crown of white bristled feathers, while females have chestnut-brown plumage with a shorter crest.",
    publishedDate: "1936-01-01",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/3/32/Afropavo_congensis_-Antwerp_Zoo_-pair-8a.jpg",
    sourceUrl: "https://en.wikipedia.org/wiki/Congo_peafowl",
    sourceName: "Photo: Frank Wouters, via Wikimedia Commons (CC BY 2.0); Wikipedia: Congo peafowl",
    keywords: ["congo peafowl", "congo peacock", "national bird", "salonga", "wildlife"],
    aliases: ["Congo peacock"],
    active: true,
    featured: false,
    verified: true,
  },
  {
    slug: "forest-elephant",
    name: "African Forest Elephant",
    category: "Nature",
    subcategory: "Wildlife Species",
    province: "Congo Basin",
    country: "DR Congo",
    shortDescription:
      "A Critically Endangered elephant species distinct from the African bush elephant, found in the DRC's rainforests and among the hardest-hit species from ivory poaching.",
    fullBiography:
      "The African forest elephant (Loxodonta cyclotis) is classified as Critically Endangered by the IUCN (2021 assessment) and has been listed on CITES Appendix I since 1989. It is native to the humid tropical forests of West and Central Africa, including the DRC's share of the Congo Basin. By a 2013 estimate, fewer than 30,000 individuals remained, and the 2021 IUCN assessment found the population had declined by more than 80% over three generations. The species is the smallest living elephant, with an average shoulder height of about 2.16 m, and is distinguished from the African bush elephant by straighter, downward-pointing tusks, smaller and more oval ears, and a nearly straight back. Forest elephants also mature and reproduce more slowly than bush elephants, which makes their populations especially slow to recover from poaching losses. Genetic evidence indicates the two African elephant species diverged at least 1.9 million years ago.",
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/b/b6/L%27%C3%A9l%C3%A9phant_de_for%C3%AAt_d%27Afrique_%28Loxodonta_cyclotis%29.jpg",
    sourceUrl: "https://en.wikipedia.org/wiki/African_forest_elephant",
    sourceName: "Photo: VIGNA christian, via Wikimedia Commons (CC BY-SA 4.0); Wikipedia: African forest elephant",
    keywords: ["forest elephant", "elephant", "congo basin", "wildlife", "critically endangered"],
    aliases: [],
    active: true,
    featured: true,
    verified: true,
  },
];

export default SEED_ITEMS;
