// The original 8 hardcoded gallery items, reshaped for congoGalleryItems.
// Used only by the one-time admin "seed" action in CongoGallery.jsx —
// not read anywhere else at runtime. Nothing here is deleted or replaced
// by later phases; new items get their own seed/entry, these stay put.
const SEED_ITEMS = [
  {
    slug: "fally-ipupa",
    name: "Fally Ipupa",
    category: "Music",
    shortDescription:
      "A modern Congolese music icon who brought Congolese sound to the world.",
    localImageKey: "fally-ipupa",
    keywords: ["musician", "singer", "rumba"],
    aliases: ["Fally"],
    active: true,
    featured: true,
    verified: true,
  },
  {
    slug: "koffi-olomide",
    name: "Koffi Olomidé",
    category: "Music",
    shortDescription:
      "One of the major voices of Congolese rumba and African music.",
    localImageKey: "koffi-olomide",
    keywords: ["musician", "rumba"],
    aliases: ["Koffi"],
    active: true,
    featured: false,
    verified: true,
  },
  {
    slug: "franco-luambo",
    name: "Franco Luambo",
    category: "Music",
    shortDescription:
      "A legendary figure whose music helped shape Congolese identity.",
    localImageKey: "franco-luambo",
    keywords: ["musician", "rumba", "tpok jazz"],
    aliases: ["Franco"],
    active: true,
    featured: false,
    verified: true,
  },
  {
    slug: "joseph-kabila",
    name: "Joseph Kabila",
    category: "Politics",
    subcategory: "Head of State",
    shortDescription:
      "President of the DRC from 2001 to 2019, succeeding his father Laurent-Désiré Kabila after his assassination.",
    fullBiography:
      "Joseph Kabila became president in January 2001 following the assassination of his father, Laurent-Désiré Kabila, initially as the country's youngest head of state. His presidency spanned the end of the Second Congo War, the 2006 and 2011 elections, and a prolonged period (2016–2019) in which he remained in office past the end of his constitutional mandate before the 2018 election. He was succeeded by Félix Tshisekedi in January 2019.",
    birthDate: "1971-06-04",
    birthplace: "Fizi, South Kivu",
    province: "South Kivu",
    localImageKey: "joseph-kabila",
    keywords: ["president", "politics", "head of state", "kabila"],
    aliases: [],
    active: true,
    featured: true,
    verified: true,
  },
  {
    slug: "kinshasa",
    name: "Kinshasa",
    category: "Cities",
    province: "Kinshasa",
    country: "DR Congo",
    shortDescription:
      "The capital city, full of energy, music, politics, creativity, and movement.",
    localImageKey: "kinshasa",
    keywords: ["capital", "city"],
    active: true,
    featured: true,
    verified: true,
  },
  {
    slug: "boulevard-du-30-juin",
    name: "Boulevard du 30 Juin",
    category: "Cities",
    city: "Kinshasa",
    country: "DR Congo",
    shortDescription:
      "One of Kinshasa’s most symbolic roads, representing movement and national life.",
    localImageKey: "boulevard-du-30-juin",
    keywords: ["boulevard", "30 juin", "kinshasa"],
    active: true,
    featured: false,
    verified: true,
  },
  {
    slug: "eastern-congo",
    name: "Eastern Congo",
    category: "History",
    subcategory: "Memory & Crisis",
    shortDescription:
      "A place of pain, resilience, and courage. Congo Unity remembers the East.",
    fullBiography:
      "Eastern Congo — principally North Kivu, South Kivu, and Ituri — has experienced recurring armed conflict since the First and Second Congo Wars, driven by a mix of regional politics, control over mineral resources, and armed groups including remnants of the forces behind the 1994 Rwandan genocide and, more recently, the M23 rebel movement. Millions have been displaced over the past three decades, and the region remains the subject of ongoing UN peacekeeping (MONUSCO) and humanitarian efforts.",
    localImageKey: "eastern-congo",
    sourceName: "Wikipedia: Kivu conflict",
    sourceUrl: "https://en.wikipedia.org/wiki/Kivu_conflict",
    keywords: ["crisis", "kivu", "memory", "m23", "conflict"],
    aliases: [],
    active: true,
    featured: false,
    verified: true,
  },
  {
    slug: "flag-of-the-drc",
    name: "Flag of the DRC",
    category: "Culture",
    subcategory: "National Symbol",
    shortDescription:
      "The flag reminds us that we are one people, even when everything tries to divide us.",
    localImageKey: "flag-of-the-drc",
    keywords: ["flag", "symbol", "national"],
    active: true,
    featured: true,
    verified: true,
  },

  // ---- Phase 2 additions below: no local photo exists for these 7, so
  // each uses a verified, freely-licensed image from Wikimedia Commons
  // instead (license + photographer checked individually, not assumed —
  // see sourceUrl/sourceName for attribution). Dates are only included
  // where a specific source confirmed them; left blank otherwise rather
  // than guessed.
  {
    slug: "werrason",
    name: "Werrason",
    category: "Music",
    subcategory: "Soukous / Ndombolo",
    shortDescription:
      "Congolese musician and bandleader of Wenge Musica Maison Mère, originally part of Wenge Musica; one of the leading soukous/ndombolo artists of the 1990s–2000s.",
    birthDate: "1965",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/8/8e/Werrason.jpg",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Werrason.jpg",
    sourceName: "Photo via Wikimedia Commons (CC BY-SA)",
    keywords: ["musician", "wenge musica", "soukous", "ndombolo"],
    aliases: [],
    active: true,
    featured: false,
    verified: true,
  },
  {
    slug: "papa-wemba",
    name: "Papa Wemba",
    category: "Music",
    subcategory: "Rumba Rock",
    shortDescription:
      "Congolese singer and a founding figure of \"Congolese rumba rock,\" closely associated with the Sape fashion movement; co-founded Zaiko Langa Langa before leading his own groups.",
    birthDate: "1949-06-14",
    deathDate: "2016-04-24",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/6/63/Papa_Wemba.jpg",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Papa_Wemba.jpg",
    sourceName: "Photo: Radio Okapi via Wikimedia Commons (CC BY 2.0)",
    keywords: ["musician", "zaiko langa langa", "sape", "rumba rock"],
    aliases: [],
    active: true,
    featured: false,
    verified: true,
  },
  {
    slug: "tabu-ley-rochereau",
    name: "Tabu Ley Rochereau",
    category: "Music",
    subcategory: "Rumba",
    shortDescription:
      "Legendary singer and bandleader (African Fiesta, later Afrisa International); one of the most important figures of Congolese rumba's golden era from the 1960s onward.",
    birthDate: "1940-11-13",
    deathDate: "2013-11-30",
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/6/66/Press_photo_of_Tabu_Ley_Rochereau_in_San_Francisco_%281980%29.jpg",
    sourceUrl:
      "https://commons.wikimedia.org/wiki/File:Press_photo_of_Tabu_Ley_Rochereau_in_San_Francisco_(1980).jpg",
    sourceName: "Photo: Philip Gould / The Rosebud Agency, via Wikimedia Commons (public domain)",
    keywords: ["musician", "african fiesta", "afrisa international", "rumba"],
    aliases: ["Rochereau"],
    active: true,
    featured: false,
    verified: true,
  },
  {
    slug: "tshala-muana",
    name: "Tshala Muana",
    category: "Music",
    subcategory: "Mutuashi",
    shortDescription:
      "Celebrated singer and dancer known as the \"Queen of Mutuashi,\" a traditional Congolese dance she helped popularize internationally; prominent from the 1980s.",
    birthDate: "1958-03-13",
    deathDate: "2022-12-10",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/8/8c/Tshala_muana_2015.jpg",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Tshala_muana_2015.jpg",
    sourceName: "Photo via Wikimedia Commons (CC BY-SA 4.0)",
    keywords: ["musician", "dancer", "mutuashi"],
    aliases: [],
    active: true,
    featured: false,
    verified: true,
  },
  {
    slug: "mbilia-bel",
    name: "Mbilia Bel",
    category: "Music",
    subcategory: "Rumba",
    shortDescription:
      "Congolese singer, one of the most prominent female voices in Congolese rumba; rose to fame performing with Tabu Ley Rochereau's Afrisa International in the 1980s before a solo career.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/a/ae/Mbilia_Bel%2C_Zaire.jpg",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Mbilia_Bel,_Zaire.jpg",
    sourceName: "Photo via Wikimedia Commons (public domain, CC0)",
    keywords: ["musician", "afrisa international", "rumba"],
    aliases: ["M'bilia Bel"],
    active: true,
    featured: false,
    verified: true,
  },
  {
    slug: "ferre-gola",
    name: "Ferre Gola",
    category: "Music",
    subcategory: "Rumba / Ndombolo",
    shortDescription:
      "Congolese singer and former member of Wenge Musica BCBG, known for his vocal range; a prominent rumba/ndombolo artist since the 2000s.",
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/f/f1/Ferr%C3%A9_Gola_2024_performance.jpg",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Ferr%C3%A9_Gola_2024_performance.jpg",
    sourceName: "Photo via Wikimedia Commons (CC BY 4.0)",
    keywords: ["musician", "wenge musica bcbg", "ndombolo"],
    aliases: ["Ferré Gola"],
    active: true,
    featured: false,
    verified: true,
  },
  {
    slug: "innossb",
    name: "Innoss'B",
    category: "Music",
    subcategory: "Afrobeat / Hip-Hop",
    shortDescription:
      "Contemporary Congolese singer, part of a newer generation blending Congolese rumba with Afrobeat and hip-hop influences.",
    birthDate: "1997-05-05",
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/6/67/Innoss%27B_%2821600557166%29.jpg",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Innoss'B_(21600557166).jpg",
    sourceName: "Photo: Abel Kavanagh / MONUSCO, via Wikimedia Commons (CC BY-SA 2.0)",
    keywords: ["musician", "rapper", "afrobeat"],
    aliases: ["Innoss B", "Innocent Balume"],
    active: true,
    featured: false,
    verified: true,
  },

  // ---- Politics: figures. Images verified individually on Wikimedia
  // Commons the same way as the Music section (license + author checked
  // per file, not assumed). Dates left blank where genuinely uncertain
  // in the historical record (e.g. Kasa-Vubu's exact birth date) rather
  // than guessed.
  {
    slug: "patrice-lumumba",
    name: "Patrice Lumumba",
    category: "Politics",
    subcategory: "Head of Government",
    shortDescription:
      "First Prime Minister of the independent Republic of the Congo in 1960; assassinated in 1961.",
    fullBiography:
      "Patrice Émery Lumumba led the independence movement that ended Belgian colonial rule and became the country's first Prime Minister when independence was declared on June 30, 1960. His government fell within months amid the Congo Crisis, and he was arrested, then killed in January 1961 in circumstances involving Congolese and Belgian actors that have been the subject of extensive historical investigation. He remains one of the most significant symbols of African independence.",
    birthDate: "1925-07-02",
    deathDate: "1961-01-17",
    birthplace: "Onalua, Kasai",
    province: "Kasai",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/d/d5/Patrice_Lumumba_official_portrait.jpg",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Patrice_Lumumba_official_portrait.jpg",
    sourceName: "Official 1960 government portrait, via Wikimedia Commons (public domain)",
    keywords: ["prime minister", "independence", "politics", "congo crisis"],
    aliases: ["Patrice Émery Lumumba"],
    active: true,
    featured: true,
    verified: true,
  },
  {
    slug: "joseph-kasa-vubu",
    name: "Joseph Kasa-Vubu",
    category: "Politics",
    subcategory: "Head of State",
    shortDescription:
      "First President of the independent Republic of the Congo, serving from 1960 to 1965.",
    fullBiography:
      "Joseph Kasa-Vubu was a founding leader of the ABAKO political party and became the country's first President at independence in June 1960. He remained in office through the turbulent Congo Crisis years until he was deposed in a 1965 coup led by Joseph-Désiré Mobutu.",
    deathDate: "1969-03-24",
    province: "Kongo Central",
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/f/ff/Joseph_Kasa-Vubu_in_1960_%28cropped%29.jpg",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Joseph_Kasa-Vubu_in_1960_(cropped).jpg",
    sourceName: "Photo: Anefo / Dutch National Archives, via Wikimedia Commons (CC0)",
    keywords: ["president", "independence", "abako", "politics"],
    aliases: [],
    active: true,
    featured: false,
    verified: true,
  },
  {
    slug: "mobutu-sese-seko",
    name: "Mobutu Sese Seko",
    category: "Politics",
    subcategory: "Head of State",
    shortDescription:
      "President from 1965 to 1997, ruling for over three decades after taking power in a coup and renaming the country Zaire.",
    fullBiography:
      "Joseph-Désiré Mobutu seized power in a 1965 coup and ruled for 32 years, renaming the country Zaire in 1971 and himself Mobutu Sese Seko. His long rule was marked by centralized one-party control and a personality cult, alongside widely documented corruption and human rights abuses. He was overthrown in 1997 during the First Congo War by forces led by Laurent-Désiré Kabila, and died in exile later that year.",
    birthDate: "1930-10-14",
    deathDate: "1997-09-07",
    birthplace: "Lisala, Équateur",
    province: "Équateur",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/7/7e/Mobutu_Sese_Seko%2C_1969.jpg",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Mobutu_Sese_Seko,_1969.jpg",
    sourceName: "Photo: © European Union, via Wikimedia Commons (attribution required)",
    keywords: ["president", "zaire", "coup", "politics", "dictator"],
    aliases: ["Joseph-Désiré Mobutu"],
    active: true,
    featured: true,
    verified: true,
  },
  {
    slug: "laurent-desire-kabila",
    name: "Laurent-Désiré Kabila",
    category: "Politics",
    subcategory: "Head of State",
    shortDescription:
      "President from 1997 to 2001, having led the rebellion that overthrew Mobutu in the First Congo War.",
    fullBiography:
      "Laurent-Désiré Kabila led the AFDL rebel coalition that overthrew Mobutu Sese Seko in 1997, becoming president and renaming Zaire back to the Democratic Republic of the Congo. His presidency was soon consumed by the outbreak of the Second Congo War in 1998. He was assassinated by a bodyguard in January 2001 and was succeeded by his son, Joseph Kabila.",
    birthDate: "1939-11-27",
    deathDate: "2001-01-16",
    birthplace: "Baudouinville (Moba), Tanganyika",
    province: "Tanganyika",
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/6/6d/Laurent_D%C3%A9sir%C3%A9_Kabila_portrait_3x4.jpg",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Laurent_D%C3%A9sir%C3%A9_Kabila_portrait_3x4.jpg",
    sourceName: "Photo: Etienne Scholasse / European Communities, via Wikimedia Commons (CC BY 4.0)",
    keywords: ["president", "afdl", "first congo war", "politics"],
    aliases: [],
    active: true,
    featured: false,
    verified: true,
  },
  {
    slug: "felix-tshisekedi",
    name: "Félix Tshisekedi",
    category: "Politics",
    subcategory: "Head of State",
    shortDescription:
      "President of the DRC since January 2019, re-elected in 2023; son of longtime opposition leader Étienne Tshisekedi.",
    fullBiography:
      "Félix Antoine Tshisekedi Tshilombo became president in January 2019 following the 2018 election, in what was widely described as the country's first peaceful transfer of power since independence. He was re-elected in the December 2023 general election. He is the son of longtime opposition figure Étienne Tshisekedi.",
    birthDate: "1963-06-13",
    province: "Kinshasa",
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/9/92/F%C3%A9lix_Tshisekedi_-_2019_%28cropped%29.jpg",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:F%C3%A9lix_Tshisekedi_-_2019_(cropped).jpg",
    sourceName: "Photo: U.S. Department of State / Michael Gross, via Wikimedia Commons (public domain)",
    keywords: ["president", "head of state", "politics", "2018 election", "2023 election"],
    aliases: ["Félix Antoine Tshisekedi Tshilombo"],
    active: true,
    featured: true,
    verified: true,
  },
  {
    slug: "etienne-tshisekedi",
    name: "Étienne Tshisekedi",
    category: "Politics",
    subcategory: "Opposition Leader",
    shortDescription:
      "Longtime opposition leader and founder of the UDPS party; a central figure in DRC's pro-democracy movement for decades.",
    fullBiography:
      "Étienne Tshisekedi wa Mulumba was a founding figure of the Union for Democracy and Social Progress (UDPS) and one of the most prominent opposition voices against both the Mobutu government and later administrations, repeatedly imprisoned and placed under house arrest over his decades of activism. He died in February 2017, before his son Félix Tshisekedi became president in 2019.",
    birthDate: "1932-12-14",
    deathDate: "2017-02-01",
    province: "Kasai-Oriental",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/6/64/%C3%89tienne_Tshisekedi.jpg",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:%C3%89tienne_Tshisekedi.jpg",
    sourceName: "Photo: Giuseppe Dominici, via Wikimedia Commons (public domain)",
    keywords: ["opposition", "udps", "politics", "pro-democracy"],
    aliases: ["Étienne Tshisekedi wa Mulumba"],
    active: true,
    featured: false,
    verified: true,
  },
  {
    slug: "denis-mukwege",
    name: "Denis Mukwege",
    category: "Politics",
    subcategory: "Statesman / Human Rights",
    shortDescription:
      "Gynecologist and human rights advocate; 2018 Nobel Peace Prize laureate for his work treating survivors of sexual violence in conflict.",
    fullBiography:
      "Denis Mukwege founded Panzi Hospital in Bukavu, South Kivu, where he and his colleagues have treated tens of thousands of survivors of sexual violence connected to the region's conflicts. He was awarded the 2018 Nobel Peace Prize jointly with Nadia Murad for efforts to end the use of sexual violence as a weapon of war, and has remained an outspoken advocate and occasional political voice on the DRC's conflicts and governance.",
    birthDate: "1955-03-01",
    birthplace: "Bukavu, South Kivu",
    province: "South Kivu",
    city: "Bukavu",
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/0/0a/Denis_Mukwege_par_Claude_Truong-Ngoc_novembre_2014_%283x4_cropped%29.jpg",
    sourceUrl:
      "https://commons.wikimedia.org/wiki/File:Denis_Mukwege_par_Claude_Truong-Ngoc_novembre_2014_(3x4_cropped).jpg",
    sourceName: "Photo: Claude Truong-Ngoc, via Wikimedia Commons (CC BY-SA 3.0)",
    keywords: ["human rights", "nobel peace prize", "panzi hospital", "bukavu", "statesman"],
    aliases: [],
    active: true,
    featured: true,
    verified: true,
  },

  // ---- Politics: institutions. No portrait photos apply; images left
  // blank (falls back to the neutral placeholder) rather than using an
  // unverified logo/building photo.
  {
    slug: "ceni-drc",
    name: "Independent National Electoral Commission (CENI)",
    category: "Politics",
    subcategory: "Institution",
    shortDescription:
      "The body responsible for organizing and overseeing elections in the DRC.",
    keywords: ["ceni", "elections", "institution", "electoral commission"],
    aliases: ["CENI", "Commission Électorale Nationale Indépendante"],
    active: true,
    featured: false,
    verified: true,
  },
  {
    slug: "parliament-of-the-drc",
    name: "Parliament of the DRC",
    category: "Politics",
    subcategory: "Institution",
    shortDescription:
      "The DRC's bicameral legislature, composed of the National Assembly and the Senate.",
    keywords: ["parliament", "national assembly", "senate", "institution", "legislature"],
    aliases: ["Parlement de la RDC"],
    active: true,
    featured: false,
    verified: true,
  },
  {
    slug: "presidency-of-the-drc",
    name: "Presidency of the DRC",
    category: "Politics",
    subcategory: "Institution",
    shortDescription:
      "The executive office of the head of state of the Democratic Republic of the Congo.",
    keywords: ["presidency", "executive", "institution", "head of state"],
    aliases: ["Présidence de la RDC"],
    active: true,
    featured: false,
    verified: true,
  },
  {
    slug: "constitutional-court-drc",
    name: "Constitutional Court",
    category: "Politics",
    subcategory: "Institution",
    shortDescription:
      "The DRC's highest court for constitutional matters, established under the 2006 Constitution.",
    keywords: ["constitutional court", "judiciary", "institution", "constitution"],
    aliases: ["Cour Constitutionnelle"],
    active: true,
    featured: false,
    verified: true,
  },

  // ---- Politics: elections. The independence/crisis/wars/agreement/
  // constitution entries that used to live here moved to the History
  // category below — they're historical narrative, not the ongoing
  // political process these election entries describe.
  {
    slug: "2006-elections",
    name: "2006 Elections",
    category: "Politics",
    subcategory: "Election",
    shortDescription:
      "The DRC's first multi-party elections since independence, held under the newly adopted 2006 Constitution; won by Joseph Kabila.",
    publishedDate: "2006-10-29",
    keywords: ["2006 elections", "joseph kabila", "election", "history"],
    aliases: [],
    active: true,
    featured: false,
    verified: true,
  },
  {
    slug: "2018-elections",
    name: "2018 Elections",
    category: "Politics",
    subcategory: "Election",
    shortDescription:
      "The election that brought Félix Tshisekedi to power, widely described as the DRC's first peaceful transfer of power since independence.",
    publishedDate: "2018-12-30",
    keywords: ["2018 elections", "felix tshisekedi", "election", "history"],
    aliases: [],
    active: true,
    featured: false,
    verified: true,
  },
  {
    slug: "2023-elections",
    name: "2023 Elections",
    category: "Politics",
    subcategory: "Election",
    shortDescription:
      "The general election in which Félix Tshisekedi was re-elected to a second term.",
    publishedDate: "2023-12-20",
    keywords: ["2023 elections", "felix tshisekedi", "election"],
    aliases: [],
    active: true,
    featured: false,
    verified: true,
  },

  // ---- History: eras, wars, agreements, constitutional milestones, and
  // maps. Every item here carries sourceName/sourceUrl per the History
  // spec, written in neutral, factual language. Images are used only
  // where a specific file's license was verified on its own Commons
  // page; left blank otherwise rather than guessing at rights.
  {
    slug: "pre-colonial-congo",
    name: "Pre-Colonial Congo: Kingdoms and Societies",
    category: "History",
    subcategory: "Historical Era",
    shortDescription:
      "Before European colonization, the Congo region was home to organized kingdoms, chiefdoms, and trading societies, including the Kongo, Luba, and Lunda.",
    fullBiography:
      "Long before the Berlin Conference and Leopold II's Congo Free State, the territory of the modern DRC held a range of organized societies — from centralized kingdoms such as Kongo (west), and Luba and Lunda (center and east), to smaller chiefdoms and decentralized communities across the Congo Basin. Bantu-speaking peoples migrated into the region beginning roughly 2000 BCE, gradually developing agriculture, ironworking, and long-distance trade networks in goods such as copper and salt. These societies developed their own systems of governance and law, and many of their cultural and artistic traditions continue to shape Congolese identity today.",
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/e/e7/African-civilizations-map-pre-colonial.svg",
    sourceUrl: "https://en.wikipedia.org/wiki/Pre-colonial_history_of_the_Democratic_Republic_of_the_Congo",
    sourceName: "Wikipedia: Pre-colonial history of the Democratic Republic of the Congo",
    keywords: ["pre-colonial", "kingdoms", "bantu", "history", "kongo", "luba", "lunda"],
    aliases: [],
    active: true,
    featured: true,
    verified: true,
  },
  {
    slug: "kingdom-of-kongo",
    name: "Kingdom of Kongo",
    category: "History",
    subcategory: "Historical Era",
    shortDescription:
      "A centralized West-Central African kingdom founded around 1390, spanning parts of the modern DRC, Angola, Congo-Brazzaville, and Gabon.",
    fullBiography:
      "The Kingdom of Kongo was founded around 1390 near the mouth of the Congo River, with its capital at Mbanza Kongo (in present-day Angola). At its height it stretched from the Atlantic coast to the Kwango River, encompassing parts of what are now the DRC, Angola, the Republic of Congo, and Gabon, and featured a centralized monarchy, provincial administration, and a shell-currency system. Portuguese explorers reached Kongo in 1483, and the kingdom's ruling elite converted to Christianity in 1491, beginning a long and often fraught relationship with Portugal. Civil war from 1665 and gradual fragmentation weakened central authority over the following two centuries; Kongo became a Portuguese vassal state in 1857, and Portugal formally abolished the titular monarchy in 1914.",
    publishedDate: "1390-01-01",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/0/01/Kingdom_of_Kongo_1600.png",
    sourceUrl: "https://en.wikipedia.org/wiki/Kingdom_of_Kongo",
    sourceName: "Map: Jarle Grøhn, via Wikimedia Commons (CC BY 3.0); Wikipedia: Kingdom of Kongo",
    keywords: ["kingdom of kongo", "mbanza kongo", "pre-colonial", "history"],
    aliases: ["Kongo Kingdom"],
    active: true,
    featured: true,
    verified: true,
  },
  {
    slug: "luba-kingdom",
    name: "Luba Kingdom",
    category: "History",
    subcategory: "Historical Era",
    shortDescription:
      "A pre-colonial kingdom centered in the Upemba Depression of southern DRC, ruled by a sacred king known as the Mulopwe.",
    fullBiography:
      "The Luba Kingdom arose in the marshy grasslands of the Upemba Depression in what is now southern DRC; historians disagree on the exact founding period, with estimates ranging from as early as the 8th century to shortly before the 15th. It was led by a sacred king, the Mulopwe, supported by court nobles (Bamfumu) and regional clan kings (Balopwe), with the Bambudye society preserving the kingdom's oral history and traditions across the realm. The kingdom weakened in the late 19th century as long-distance trade networks were disrupted by East African traders seeking slaves and ivory, and collapsed in 1889 following a succession dispute, after which its territory was absorbed into the Congo Free State.",
    sourceUrl: "https://en.wikipedia.org/wiki/Luba_Kingdom",
    sourceName: "Wikipedia: Luba Kingdom",
    keywords: ["luba kingdom", "mulopwe", "upemba", "pre-colonial", "history"],
    aliases: ["Luba Empire"],
    active: true,
    featured: false,
    verified: true,
  },
  {
    slug: "lunda-empire",
    name: "Lunda Empire",
    category: "History",
    subcategory: "Historical Era",
    shortDescription:
      "A pre-colonial empire centered in what is now Katanga, ruled by a paramount king known as the Mwata Yamvo, at its height covering around 300,000 km².",
    fullBiography:
      "The Lunda Empire was established in the 17th century, with its central state in what is now Katanga Province, and grew through a system of tributary chieftainships that retained local autonomy in exchange for allegiance to a paramount ruler, the Mwata Yamvo, under a tradition of \"perpetual kingship\" in which successors adopted their predecessors' titles and roles. At its 19th-century height, the empire's influence extended across roughly 300,000 km² spanning parts of the modern DRC, Angola, and Zambia. It collapsed after invasions by Chokwe forces armed with firearms in the late 19th century, and by 1887 its former territory had been divided among Portuguese Angola, the Congo Free State, and British-administered Northern Rhodesia.",
    publishedDate: "1665-01-01",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/f/fb/Lunda_Empire.png",
    sourceUrl: "https://en.wikipedia.org/wiki/Lunda_Empire",
    sourceName: "Map: U.S. Library of Congress, via Wikimedia Commons (public domain); Wikipedia: Lunda Empire",
    keywords: ["lunda empire", "mwata yamvo", "katanga", "pre-colonial", "history"],
    aliases: ["Lunda Kingdom"],
    active: true,
    featured: false,
    verified: true,
  },
  {
    slug: "congo-free-state",
    name: "Congo Free State",
    category: "History",
    subcategory: "Historical Era",
    shortDescription:
      "A personal colony of Belgium's King Leopold II from 1885 to 1908, notorious for a forced-labor rubber economy and widespread atrocities.",
    fullBiography:
      "The Congo Free State was established on August 1, 1885, after the Berlin Conference recognized King Leopold II of Belgium as sovereign over the territory — not as a Belgian colony, but as his personal possession, administered from Brussels through appointed officials. Leopold's administration ran a forced-labor system built around rubber and ivory quotas, enforced by the Force Publique, which caused mass suffering, mutilation, and death across the territory. Estimates of the death toll vary widely among historians, from roughly one million to ten million, reflecting the difficulty of counting a population that was never systematically recorded. International exposure of the abuses — including Roger Casement's 1903 report and the advocacy of the Congo Reform Association — forced Leopold to relinquish personal control, and Belgium formally annexed the territory as the Belgian Congo on November 15, 1908.",
    publishedDate: "1885-08-01",
    sourceName: "Wikipedia: Congo Free State",
    sourceUrl: "https://en.wikipedia.org/wiki/Congo_Free_State",
    keywords: ["congo free state", "leopold ii", "history", "colonial era", "1885"],
    aliases: ["État indépendant du Congo", "Independent State of the Congo"],
    active: true,
    featured: true,
    verified: true,
  },
  {
    slug: "belgian-congo",
    name: "Belgian Congo",
    category: "History",
    subcategory: "Historical Era",
    shortDescription:
      "The formal Belgian colony that succeeded the Congo Free State, lasting from 1908 until independence in 1960.",
    fullBiography:
      "Belgium's parliament voted to annex the Congo Free State on October 18, 1908, with the annexation taking formal effect on November 15, 1908, ending Leopold II's personal rule. As a state colony, the Belgian Congo was organized into provinces, districts, and territories under a Governor-General, with local indigenous courts operating under colonial oversight. The territory supplied significant raw materials during both World Wars, including uranium used in the Manhattan Project during World War II. Colonial rule continued, with limited political participation introduced only shortly before independence — the first municipal elections open to Black voters were held in 1957 — until the Belgian Congo became independent as the Republic of the Congo on June 30, 1960.",
    publishedDate: "1908-11-15",
    sourceName: "Wikipedia: Belgian Congo",
    sourceUrl: "https://en.wikipedia.org/wiki/Belgian_Congo",
    keywords: ["belgian congo", "colonial era", "history", "1908", "1960"],
    aliases: ["Congo Belge"],
    active: true,
    featured: true,
    verified: true,
  },
  {
    slug: "independence-1960",
    name: "Independence (1960)",
    category: "History",
    subcategory: "Historical Event",
    shortDescription:
      "The Democratic Republic of the Congo declared independence from Belgium on June 30, 1960.",
    fullBiography:
      "Independence was granted on June 30, 1960, following a Round Table Conference held in Brussels earlier that year, in which Belgium agreed to a rapid transfer of power after growing nationalist unrest in the colony. Joseph Kasa-Vubu became the country's first president and Patrice Lumumba its first prime minister. The new state, initially named the Republic of the Congo, had almost no Congolese-trained administrators, army officers, or professionals at independence — a legacy of Belgian colonial policy — which contributed directly to the instability of the Congo Crisis that followed within days.",
    publishedDate: "1960-06-30",
    sourceName: "Wikipedia: Belgian Congo",
    sourceUrl: "https://en.wikipedia.org/wiki/Belgian_Congo",
    keywords: ["independence", "1960", "belgium", "history"],
    aliases: ["Congolese independence", "30 June 1960"],
    active: true,
    featured: true,
    verified: true,
  },
  {
    slug: "congo-crisis",
    name: "Congo Crisis",
    category: "History",
    subcategory: "Historical Event",
    shortDescription:
      "A period of political upheaval from 1960 to 1965 following independence, including the Katanga and South Kasai secessions and UN intervention.",
    fullBiography:
      "Days after independence, a mutiny in the Force Publique triggered a broader breakdown of order. Katanga, led by Moïse Tshombe, and South Kasai seceded shortly afterward, and the United Nations deployed a peacekeeping mission (ONUC) to help stabilize the country. Prime Minister Patrice Lumumba was dismissed by President Kasa-Vubu in a constitutional standoff, later captured and killed in January 1961. Colonel Joseph-Désiré Mobutu seized power in a first coup in 1960 and again, definitively, in 1965, ending the crisis period.",
    publishedDate: "1960-07-05",
    sourceName: "Wikipedia: Congo Crisis",
    sourceUrl: "https://en.wikipedia.org/wiki/Congo_Crisis",
    keywords: ["congo crisis", "katanga", "secession", "history", "1960s"],
    aliases: [],
    active: true,
    featured: false,
    verified: true,
  },
  {
    slug: "zaire-era",
    name: "Zaire Era",
    category: "History",
    subcategory: "Historical Era",
    shortDescription:
      "The 1971–1997 period under President Mobutu Sese Seko, during which the country was renamed Zaire as part of his authenticité program.",
    fullBiography:
      "On October 27, 1971, President Mobutu Sese Seko renamed the country Zaire as part of a broader authenticité policy intended to move away from colonial-era names and symbols — cities were renamed (Léopoldville became Kinshasa), citizens were required to adopt African names, and Western dress was officially discouraged in favor of the abacost. Politically, the era was defined by one-party rule under Mobutu's Popular Movement of the Revolution, with power concentrated in the presidency. The economy declined sharply over the period amid mismanagement and widespread corruption. The Zaire era ended as Mobutu fled the country on May 17, 1997, during the First Congo War; the new government under Laurent-Désiré Kabila restored the name Democratic Republic of the Congo on May 21, 1997.",
    publishedDate: "1971-10-27",
    sourceName: "Wikipedia: Zaire",
    sourceUrl: "https://en.wikipedia.org/wiki/Zaire",
    keywords: ["zaire", "mobutu", "authenticite", "history", "1971", "1997"],
    aliases: ["Mobutu era"],
    active: true,
    featured: true,
    verified: true,
  },
  {
    slug: "zairianization",
    name: "Zaireanization",
    category: "History",
    subcategory: "Historical Event",
    shortDescription:
      "A 1973–1974 economic policy under Mobutu Sese Seko that nationalized foreign-owned businesses and redistributed them to Zairian nationals.",
    fullBiography:
      "On November 30, 1973, Mobutu Sese Seko announced the nationalization of foreign-owned plantations, ranches, and commercial businesses as an economic extension of his authenticité policy. Ownership was transferred to roughly 300 politically connected Zairians — mostly senior party and government officials — with smaller enterprises allocated to local notables. Many new owners lacked business experience and rapidly liquidated inventories for short-term profit, causing severe shortages of food, textiles, and medicine and driving prices sharply higher. By 1977, the resulting economic collapse forced Mobutu to begin reversing the policy (a process known as \"retrocession\") and to court foreign investors back to the country.",
    publishedDate: "1973-11-30",
    sourceName: "Wikipedia: Authenticité (Zaire)",
    sourceUrl: "https://en.wikipedia.org/wiki/Zairianization",
    keywords: ["zaireanization", "zairianization", "mobutu", "nationalization", "economy", "history"],
    aliases: ["Zairianization"],
    active: true,
    featured: false,
    verified: true,
  },
  {
    slug: "first-congo-war",
    name: "First Congo War",
    category: "History",
    subcategory: "Historical Event",
    shortDescription:
      "A 1996–1997 conflict that toppled Mobutu Sese Seko and brought Laurent-Désiré Kabila to power.",
    fullBiography:
      "The war began in October 1996 when the Alliance of Democratic Forces for the Liberation of Congo-Zaire (AFDL), led by Laurent-Désiré Kabila and backed by Rwanda and Uganda, launched an offensive from the east, initially targeting Hutu militias and refugee camps in the aftermath of the 1994 Rwandan genocide. Facing a collapsing and demoralized army, Mobutu Sese Seko's government fell in a matter of months; Kabila's forces took Kinshasa on May 17, 1997, and Kabila declared himself president, renaming Zaire the Democratic Republic of the Congo.",
    sourceName: "Wikipedia: First Congo War",
    sourceUrl: "https://en.wikipedia.org/wiki/First_Congo_War",
    keywords: ["first congo war", "1996", "1997", "mobutu", "kabila", "history"],
    aliases: [],
    active: true,
    featured: false,
    verified: true,
  },
  {
    slug: "second-congo-war",
    name: "Second Congo War",
    category: "History",
    subcategory: "Historical Event",
    shortDescription:
      "A 1998–2003 multi-national conflict involving several African states, among the deadliest conflicts since World War II.",
    fullBiography:
      "War broke out in August 1998 after President Laurent-Désiré Kabila moved to expel the Rwandan and Ugandan forces that had helped bring him to power the previous year, prompting a new rebellion backed by Rwanda and Uganda. At its height, the war drew in the armed forces of at least six other African nations, either supporting Kabila's government (including Zimbabwe, Angola, and Namibia) or the rebel factions. A 1999 Lusaka Ceasefire Agreement failed to fully halt the fighting. Estimates of the war's toll vary widely, but it is often cited as the deadliest conflict since World War II, with millions of deaths attributed mostly to disease and malnutrition amid the collapse of health and food systems. The war formally ended with the 2002 Global and All-Inclusive Agreement, though armed conflict has continued intermittently in the eastern DRC since.",
    sourceName: "Wikipedia: Second Congo War",
    sourceUrl: "https://en.wikipedia.org/wiki/Second_Congo_War",
    keywords: ["second congo war", "1998", "2003", "history", "conflict"],
    aliases: ["Africa's World War"],
    active: true,
    featured: false,
    verified: true,
  },
  {
    slug: "inter-congolese-dialogue",
    name: "Inter-Congolese Dialogue",
    category: "History",
    subcategory: "Historical Event",
    shortDescription:
      "The 2001–2002 peace negotiation process among the DRC's warring parties, facilitated by former Botswana president Ketumile Masire, that produced the agreements ending the Second Congo War.",
    fullBiography:
      "The Inter-Congolese Dialogue officially opened in Addis Ababa on October 15, 2001, facilitated by former Botswana president Sir Ketumile Masire under a mandate from the Organisation of African Unity. It brought together the DRC government, the Rwandan-backed RCD-Goma and Ugandan-backed MLC rebel movements, and unarmed opposition and civil-society groups. Talks continued at Sun City, South Africa, from February 25 to April 12, 2002, producing the partial Sun City Agreement, and negotiations concluded later that year with the more comprehensive Global and All-Inclusive Agreement.",
    publishedDate: "2001-10-15",
    sourceName: "Wikipedia: Sun City Agreement",
    sourceUrl: "https://en.wikipedia.org/wiki/Sun_City_Agreement",
    keywords: ["inter-congolese dialogue", "ketumile masire", "peace process", "history"],
    aliases: ["ICD"],
    active: true,
    featured: false,
    verified: true,
  },
  {
    slug: "global-and-all-inclusive-agreement",
    name: "Global and All-Inclusive Agreement (2002)",
    category: "History",
    subcategory: "Peace Agreement",
    shortDescription:
      "The December 2002 peace accord that formally ended the Second Congo War and established a transitional government, building on the earlier Sun City Agreement.",
    fullBiography:
      "As the Second Congo War wound down, delegates to the Inter-Congolese Dialogue signed the Sun City Agreement on April 2, 2002 — a partial accord that most, but not all, of the warring parties endorsed. Negotiations continued under UN mediation, and on December 16–17, 2002, the parties signed the more comprehensive Global and All-Inclusive Agreement on the Transition in the DRC, formally ending the war and setting up a power-sharing transitional government that led to the 2006 elections.",
    publishedDate: "2002-12-17",
    sourceName: "Wikipedia: Sun City Agreement",
    sourceUrl: "https://en.wikipedia.org/wiki/Sun_City_Agreement",
    keywords: ["peace agreement", "sun city", "transitional government", "2002"],
    aliases: ["Sun City Agreement", "Pretoria Accord"],
    active: true,
    featured: false,
    verified: true,
  },
  {
    slug: "transitional-government",
    name: "Transitional Government of the DRC (2003–2006)",
    category: "History",
    subcategory: "Historical Era",
    shortDescription:
      "The power-sharing \"1+4\" government established by the Global and All-Inclusive Agreement, which governed the DRC until the 2006 elections.",
    fullBiography:
      "The transitional government took office under a formula known as \"1+4\": Joseph Kabila was sworn in as transitional president on April 7, 2003, alongside four vice presidents representing the former belligerents and the unarmed opposition — Abdoulaye Yerodia Ndombasi for Kabila's government, Jean-Pierre Bemba for the MLC, Azarias Ruberwa for the RCD-Goma, and Arthur Z'Ahidi Ngoma for the political opposition — who took office on July 17, 2003. The transitional period oversaw the drafting and adoption of the 2006 Constitution and ended with the completion of the 2006 general election, when Kabila was sworn in as elected president on December 6, 2006.",
    publishedDate: "2003-04-07",
    sourceName: "Wikipedia: Transitional Government of the Democratic Republic of the Congo",
    sourceUrl: "https://en.wikipedia.org/wiki/Transitional_Government_of_the_Democratic_Republic_of_the_Congo",
    keywords: ["transitional government", "1+4", "power-sharing", "history"],
    aliases: ["1+4 government"],
    active: true,
    featured: false,
    verified: true,
  },
  {
    slug: "2006-constitution",
    name: "2006 Constitution",
    category: "History",
    subcategory: "Constitutional Milestone",
    shortDescription:
      "The DRC's current constitution, adopted by referendum in December 2005 and promulgated in February 2006.",
    fullBiography:
      "Drafted during the 2003–2006 transitional period established by the Global and All-Inclusive Agreement, the constitution was approved by popular referendum in December 2005 and promulgated by transitional president Joseph Kabila on February 18, 2006. It is the DRC's sixth constitution since 1960, and the first adopted directly by popular vote. It established a decentralized semi-presidential republic with a separation of powers among the executive, legislature, and judiciary, and divided the country into provinces with defined central and provincial authority.",
    publishedDate: "2006-02-18",
    sourceName: "Wikipedia: Constitution of the Democratic Republic of the Congo",
    sourceUrl: "https://en.wikipedia.org/wiki/Constitution_of_the_Democratic_Republic_of_the_Congo",
    keywords: ["constitution", "2006", "referendum", "constitutional milestone"],
    aliases: [],
    active: true,
    featured: false,
    verified: true,
  },
  {
    slug: "first-peaceful-transfer-of-power",
    name: "First Peaceful Transfer of Power (2019)",
    category: "History",
    subcategory: "National Milestone",
    shortDescription:
      "Félix Tshisekedi's January 2019 inauguration was widely described as the DRC's first peaceful transfer of presidential power since independence.",
    fullBiography:
      "Following the December 30, 2018 general election, Félix Tshisekedi was declared the winner and sworn in as president on January 24, 2019, succeeding Joseph Kabila. The transition was widely described in DRC and abroad as the country's first peaceful transfer of power between an outgoing and an incoming president since independence in 1960. The result was disputed, however: runner-up Martin Fayulu alleged the vote had been manipulated in Tshisekedi's favor and challenged it before the Constitutional Court, and independent observers including the Catholic Church's election-monitoring mission also raised doubts about the official count.",
    publishedDate: "2019-01-24",
    sourceName: "Wikipedia: 2018 Democratic Republic of the Congo general election",
    sourceUrl: "https://en.wikipedia.org/wiki/2018_Democratic_Republic_of_the_Congo_general_election",
    keywords: ["peaceful transfer of power", "2019", "tshisekedi", "national milestone", "history"],
    aliases: [],
    active: true,
    featured: true,
    verified: true,
  },
  {
    slug: "name-changes-of-the-congo",
    name: "Name Changes of the Congo",
    category: "History",
    subcategory: "National Milestone",
    shortDescription:
      "The country has carried five official names since 1885, each marking a distinct political era.",
    fullBiography:
      "The territory has been renamed five times: the Congo Free State (1885–1908), the Belgian Congo (1908–1960), the Republic of the Congo at independence in 1960 (often called Congo-Léopoldville to distinguish it from the neighboring Republic of the Congo), the Democratic Republic of the Congo from August 1964 under the Luluabourg Constitution, Zaire from October 27, 1971 under Mobutu Sese Seko's authenticité program, and back to the Democratic Republic of the Congo from May 21, 1997 under Laurent-Désiré Kabila.",
    sourceName: "Britannica: Why did DR Congo change its name?",
    sourceUrl: "https://www.britannica.com/question/Why-did-DR-Congo-change-its-name",
    keywords: ["name change", "zaire", "congo-leopoldville", "national milestone", "history"],
    aliases: [],
    active: true,
    featured: false,
    verified: true,
  },

  // ---- History: maps. Only Commons files with a clearly verified,
  // individually-checked license were used.
  {
    slug: "map-congo-free-state-1896",
    name: "1896 Map of the Congo Free State",
    category: "History",
    subcategory: "Historic Map",
    shortDescription:
      "A cartographic map of the Congo Free State published in 1896 by Léon de Moor, held by the Library of Congress.",
    fullBiography:
      "Published in 1896 by cartographer Léon de Moor for J. Lebègue & Co., this map depicts the Congo Free State roughly a decade before Belgium's 1908 annexation ended Leopold II's personal rule. It shows the territory's early administrative concession zones and settlements as recorded during that period, and is held today by the Library of Congress via the World Digital Library.",
    publishedDate: "1896-01-01",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/7/7e/Map_of_the_Belgian_Congo_WDL59.png",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Map_of_the_Belgian_Congo_WDL59.png",
    sourceName:
      "Map: Léon de Moor, published by J. Lebègue & Co. (1896) — Library of Congress / World Digital Library, via Wikimedia Commons (public domain)",
    keywords: ["map", "congo free state", "1896", "historic map", "cartography"],
    aliases: [],
    active: true,
    featured: false,
    verified: true,
  },
  {
    slug: "map-drc-provinces",
    name: "Map of the DRC's Provinces",
    category: "History",
    subcategory: "Historic Map",
    shortDescription:
      "A reference map showing the Democratic Republic of the Congo's present-day borders and administrative divisions.",
    fullBiography:
      "This modern reference map shows the DRC's current national borders, useful for orienting the country's 26 provinces (following the 2015 territorial reorganization) against the historical eras, cities, and events documented elsewhere in this gallery.",
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/1/1b/Democratic_Republic_of_the_Congo_adm_location_map.svg",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Democratic_Republic_of_the_Congo_adm_location_map.svg",
    sourceName: "Map: NordNordWest, via Wikimedia Commons (CC BY-SA 3.0 DE)",
    keywords: ["map", "provinces", "administrative divisions", "cartography"],
    aliases: [],
    active: true,
    featured: false,
    verified: true,
  },

  // ---- Cities: major DRC cities beyond Kinshasa. No local photos exist
  // for these, so each uses a Commons image verified on its own file
  // page (license + author checked individually, same discipline as
  // Music/Politics/History).
  {
    slug: "lubumbashi",
    name: "Lubumbashi",
    category: "Cities",
    province: "Haut-Katanga",
    country: "DR Congo",
    shortDescription:
      "The DRC's second-largest city and mining capital, at the heart of the copper and cobalt belt in the southeast.",
    fullBiography:
      "Founded in 1910 as a base for regional mining, Lubumbashi is the capital of Haut-Katanga Province and the country's principal industrial and mining hub, home to many of the DRC's largest copper and cobalt companies. The DRC produces more than 3% of the world's copper and roughly half its cobalt, most of it from the Katanga region. Known as \"the capital of copper,\" the city is the transportation and commercial center for mineral products from nearby mining towns including Likasi and Kolwezi.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/8/8d/Lubumbashi-downtown-banner.jpg",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Lubumbashi-downtown-banner.jpg",
    sourceName: "Photo: Oasisk, via Wikimedia Commons (CC BY-SA 3.0)",
    keywords: ["lubumbashi", "katanga", "haut-katanga", "mining", "copper", "cobalt", "city"],
    aliases: ["Élisabethville"],
    active: true,
    featured: true,
    verified: true,
  },
  {
    slug: "goma",
    name: "Goma",
    category: "Cities",
    province: "North Kivu",
    country: "DR Congo",
    shortDescription:
      "The capital of North Kivu, on the shore of Lake Kivu at the foot of the active Mount Nyiragongo volcano.",
    fullBiography:
      "Goma sits on the northern shore of Lake Kivu near the DRC's border with Rwanda, about 12 km south of Mount Nyiragongo, one of the world's most active volcanoes. A 2002 eruption killed more than 250 people and left 120,000 homeless; a 2021 eruption destroyed thousands of homes. Goma has long served as a hub for humanitarian operations in eastern Congo amid recurring conflict in North Kivu, including the M23 rebel offensive that took control of the city in January 2025.",
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/5/50/Goma%2C_Nord_Kivu%2C_RD_Congo_-_Vue_a%C3%A9rienne_partielle_de_la_ville_de_Goma._%2823720614532%29.jpg",
    sourceUrl:
      "https://commons.wikimedia.org/wiki/File:Goma,_Nord_Kivu,_RD_Congo_-_Vue_a%C3%A9rienne_partielle_de_la_ville_de_Goma._(23720614532).jpg",
    sourceName: "Photo: MONUSCO/Michael Ali, via Wikimedia Commons (CC BY-SA 2.0)",
    keywords: ["goma", "north kivu", "lake kivu", "nyiragongo", "city"],
    aliases: [],
    active: true,
    featured: true,
    verified: true,
  },
  {
    slug: "kisangani",
    name: "Kisangani",
    category: "Cities",
    province: "Tshopo",
    country: "DR Congo",
    shortDescription:
      "The DRC's fifth-largest city, a historic river port at the northernmost navigable point of the Congo River.",
    fullBiography:
      "Founded by Europeans in 1883 and known successively as Falls Station and Stanleyville, Kisangani is the capital of Tshopo Province and sits at the junction of the Congo, Tshopo, and Lindi rivers, about 80 km from the equator. It marks the northern limit of navigation for large cargo vessels on the Congo River between Kinshasa and Kisangani, making it a key trading link between eastern and western Congo.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/c/cb/Aerial_view_of_the_Congo_River_near_Kisangani.jpg",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Aerial_view_of_the_Congo_River_near_Kisangani.jpg",
    sourceName: "Photo: MONUSCO/Myriam Asmani, via Wikimedia Commons (CC BY-SA 2.0)",
    keywords: ["kisangani", "tshopo", "congo river", "city"],
    aliases: ["Stanleyville", "Falls Station"],
    active: true,
    featured: false,
    verified: true,
  },
  {
    slug: "bukavu",
    name: "Bukavu",
    category: "Cities",
    province: "South Kivu",
    country: "DR Congo",
    shortDescription:
      "The capital of South Kivu, on the southwestern shore of Lake Kivu, known for its Belgian-era art deco architecture.",
    fullBiography:
      "Bukavu sits on a peninsula at the southwestern edge of Lake Kivu, across the Ruzizi River from Rwanda, and serves as South Kivu's provincial capital and a regional commercial and lake-port center. The city retains more than 100 art deco buildings from the Belgian colonial period. Like much of eastern Congo, Bukavu has been affected by recurring conflict, including its capture by M23 rebels in February 2025.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/0/03/Laville_de_bukavu_vue_du_lac.jpg",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Laville_de_bukavu_vue_du_lac.jpg",
    sourceName: "Photo: Cedrickarungu921, via Wikimedia Commons (CC0)",
    keywords: ["bukavu", "south kivu", "lake kivu", "city"],
    aliases: [],
    active: true,
    featured: false,
    verified: true,
  },
  {
    slug: "mbuji-mayi",
    name: "Mbuji-Mayi",
    category: "Cities",
    province: "Kasaï-Oriental",
    country: "DR Congo",
    shortDescription:
      "The capital of Kasaï-Oriental and the traditional center of the DRC's industrial diamond mining industry.",
    fullBiography:
      "Mbuji-Mayi, formerly known as Bakwanga, is among the DRC's most populous cities and sits atop one of the largest known diamond deposits in the world. The state mining company MIBA, headquartered in the city, was once the source of a majority of the world's industrial diamonds. Despite this mineral wealth, the city has faced significant economic hardship in recent decades.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/5/5d/A%C3%A9roport_de_Mbuji-Mayi.jpg",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:A%C3%A9roport_de_Mbuji-Mayi.jpg",
    sourceName: "Photo: MONUSCO/Myriam Asmani, via Wikimedia Commons (CC BY-SA 2.0)",
    keywords: ["mbuji-mayi", "kasai-oriental", "diamonds", "mining", "city"],
    aliases: ["Bakwanga"],
    active: true,
    featured: false,
    verified: true,
  },
  {
    slug: "matadi",
    name: "Matadi",
    category: "Cities",
    province: "Kongo Central",
    country: "DR Congo",
    shortDescription:
      "The DRC's chief seaport and the capital of Kongo Central province, on the Congo River near the Atlantic coast.",
    fullBiography:
      "Founded by Henry Morton Stanley in 1879, Matadi is the last navigable port on the Congo River before the rapids that block further passage upstream, making it the DRC's principal maritime gateway. The Matadi–Kinshasa railway, built between 1890 and 1898, connected the port to the interior. The Matadi Bridge, completed in 1983, is the only bridge across the main stem of the Congo River.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/9/96/Matadi_Bridge_DR_Congo.jpg",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Matadi_Bridge_DR_Congo.jpg",
    sourceName: "Photo: Christos Immanuel, via Wikimedia Commons (CC BY-SA 4.0)",
    keywords: ["matadi", "kongo central", "port", "matadi bridge", "city"],
    aliases: [],
    active: true,
    featured: false,
    verified: true,
  },
  {
    slug: "kananga",
    name: "Kananga",
    category: "Cities",
    province: "Kasaï-Central",
    country: "DR Congo",
    shortDescription:
      "The capital of Kasaï-Central and one of the DRC's most populous cities, formerly known as Luluabourg.",
    fullBiography:
      "Founded around a station established by explorer Hermann Wissmann in the 1880s and later renamed Luluabourg after a nearby railway stop, the city was renamed Kananga in 1966 during Mobutu Sese Seko's campaign to replace colonial-era place names. It served briefly as the seat of the secessionist South Kasai state in the early 1960s and hosted the drafting of the DRC's first Congolese-written constitution in 1964. Kananga is today the capital of Kasaï-Central Province and one of the country's most populous urban centers.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/f/f6/Aerial_photograph_of_Kananga.jpg",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Aerial_photograph_of_Kananga.jpg",
    sourceName: "Photo: MONUSCO/Myriam Asmani, via Wikimedia Commons (CC BY-SA 2.0)",
    keywords: ["kananga", "kasai-central", "luluabourg", "city"],
    aliases: ["Luluabourg"],
    active: true,
    featured: false,
    verified: true,
  },
  {
    slug: "kolwezi",
    name: "Kolwezi",
    category: "Cities",
    province: "Lualaba",
    country: "DR Congo",
    shortDescription:
      "The capital of Lualaba Province, known as the DRC's mining center for copper and cobalt, home to some of the world's largest cobalt reserves.",
    fullBiography:
      "Industrial development at Kolwezi began around 1901, and the Belgian mining company Union Minière du Haut Katanga (predecessor of the state-owned Gécamines) established operations there in 1906, building the city into a major copper-mining center. Today Kolwezi sits atop a large share of the world's known cobalt reserves and remains central to global battery-metal supply chains, alongside continued copper production. The city was also the site of a violent 1978 conflict remembered as the Battle of Kolwezi.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/c/c7/Kamoto_Mine_-_panoramio.jpg",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Kamoto_Mine_-_panoramio.jpg",
    sourceName: "Photo: Martin Tuchscherer, via Wikimedia Commons (CC BY-SA 3.0)",
    keywords: ["kolwezi", "lualaba", "cobalt", "copper", "mining", "city"],
    aliases: [],
    active: true,
    featured: true,
    verified: true,
  },
  {
    slug: "boma",
    name: "Boma",
    category: "Cities",
    province: "Kongo Central",
    country: "DR Congo",
    shortDescription:
      "A historic port city on the Congo River near the Atlantic coast, and the former capital of the Congo Free State and Belgian Congo.",
    fullBiography:
      "Boma served as the capital of the Congo Free State and later the Belgian Congo from 1886 until 1923, when the colonial administration relocated the capital to Léopoldville (Kinshasa). Located roughly 100 km upstream from the Atlantic Ocean on the Congo River, Boma remains an active port handling exports including timber, bananas, cocoa, and palm products, and sits near the river's mouth, close to the country's border with Angola.",
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/f/f0/Boma%2C_Congo%2C_ca._1900-1915_%28IMP-CSCNWW33-OS11-74%29.jpg",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Boma,_Congo,_ca._1900-1915_(IMP-CSCNWW33-OS11-74).jpg",
    sourceName:
      "Photo: International Mission Photography Archive, Congo Balolo Mission collection, via Wikimedia Commons (public domain, pre-1931)",
    keywords: ["boma", "kongo central", "port", "former capital", "congo free state", "city"],
    aliases: [],
    active: true,
    featured: false,
    verified: true,
  },
  {
    slug: "bunia",
    name: "Bunia",
    category: "Cities",
    province: "Ituri",
    country: "DR Congo",
    shortDescription:
      "The capital of Ituri Province, established in 1946 to support the nearby Kilo-Moto gold mines.",
    fullBiography:
      "Bunia was founded in 1946 as an administrative center serving the Kilo-Moto gold mines, among the largest gold-mining operations in Africa, and sits on a plateau near Lake Albert in the Albertine Rift. It became the capital of Ituri Province following that province's creation in 2005. Bunia and the surrounding Ituri region saw intense fighting during the Ituri conflict between Hema and Lendu communities, particularly during the Second Congo War, and the city remains an important administrative and economic center for the province.",
    publishedDate: "1946-01-01",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/c/c4/Bunia.JPG",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Bunia.JPG",
    sourceName: "Photo: HokieRNB (Russell N. Brown), via Wikimedia Commons (public domain)",
    keywords: ["bunia", "ituri", "kilo-moto", "city"],
    aliases: [],
    active: true,
    featured: false,
    verified: true,
  },
  {
    slug: "uvira",
    name: "Uvira",
    category: "Cities",
    province: "South Kivu",
    country: "DR Congo",
    shortDescription:
      "A port city at the northern tip of Lake Tanganyika, in South Kivu, and a key trade hub bordering Burundi.",
    fullBiography:
      "Uvira sits at the northernmost point of Lake Tanganyika in South Kivu Province, near the DRC's border with Burundi. It developed from the early 1900s as a garrison of the Congo Free State, serving as an entry point via Lake Tanganyika and a base for monitoring nearby German East Africa. Its lake port, Kalundu, connects Uvira by boat to Kalemie, Kigoma (Tanzania), Bujumbura (Burundi), and Mpulungu (Zambia), making the city a regional trade hub. Uvira gained official city status by presidential decree in 2018, the second in South Kivu after Bukavu.",
    publishedDate: "2018-01-01",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/f/fb/VILLE_D%27UVIRA.jpg",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:VILLE_D%27UVIRA.jpg",
    sourceName: "Photo: Mukengere karume, via Wikimedia Commons (CC0)",
    keywords: ["uvira", "south kivu", "lake tanganyika", "city"],
    aliases: [],
    active: true,
    featured: false,
    verified: true,
  },
];

export default SEED_ITEMS;
